// SPDX-License-Identifier: UNLICENSED

pragma solidity 0.8.14;

// Using @openzeppelin/contracts-upgradeable@4.6.0
import "contracts-upgradeable-4.6.0/token/ERC721/ERC721Upgradeable.sol";
import "contracts-upgradeable-4.6.0/token/ERC721/extensions/ERC721EnumerableUpgradeable.sol";
import "contracts-upgradeable-4.6.0/token/ERC721/extensions/ERC721BurnableUpgradeable.sol";
import "contracts-upgradeable-4.6.0/token/ERC721/extensions/ERC721PausableUpgradeable.sol";
import "contracts-upgradeable-4.6.0/access/AccessControlEnumerableUpgradeable.sol";
import "contracts-upgradeable-4.6.0/utils/ContextUpgradeable.sol";
import "contracts-upgradeable-4.6.0/utils/CountersUpgradeable.sol";
import "contracts-upgradeable-4.6.0/proxy/utils/Initializable.sol";
import "contracts-upgradeable-4.6.0/proxy/utils/UUPSUpgradeable.sol";
import "contracts-upgradeable-4.6.0/token/ERC20/utils/SafeERC20Upgradeable.sol";

/**
 * @dev {ERC721} token, including:
 *
 *  - ability for holders to burn (destroy) their tokens
 *  - a minter role that allows for token minting (creation)
 *  - a pauser role that allows to stop all token transfers
 *  - token ID and URI autogeneration
 *
 * This contract uses {AccessControl} to lock permissioned functions using the
 * different roles - head to its documentation for details.
 *
 * The account that deploys the contract will be granted the minter and pauser
 * roles, as well as the default admin role, which will let it grant both minter
 * and pauser roles to other accounts.
 */
contract TheGreatWaveNFT is
    Initializable,
    ContextUpgradeable,
    AccessControlEnumerableUpgradeable,
    ERC721EnumerableUpgradeable,
    ERC721BurnableUpgradeable,
    ERC721PausableUpgradeable,
    UUPSUpgradeable
{
    using AddressUpgradeable for address payable;
    using StringsUpgradeable for uint256;
    using CountersUpgradeable for CountersUpgradeable.Counter;
    using SafeERC20Upgradeable for IERC20Upgradeable;

    address constant ADMIN =
        address(0xB9a81e121d8C9D619682bB9dDB6823439178F2f8);

    bytes32 public constant MINTER_ROLE = keccak256("MINTER_ROLE");
    bytes32 public constant PAUSER_ROLE = keccak256("PAUSER_ROLE");

    address constant STAKE_VAULT_TOKEN =
        address(0x44a9cE69eF2a71A9630697CA5CaB3f4aDaF8f90d); // WVP
    address constant STAKE_VAULT =
        address(0x8888888818b6e5BBdF1F73c5F3A7F73b2454d2cA); // TGW

    uint256 constant AVERAGE_DURATION = 1 weeks; // used to calculate ownerAverageBalanceOfStakedVault

    address constant WBNB = 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c;

    struct TypeMintFee {
        address payable to;
        uint256 fee; // mint fee in native token
    }
    struct TypeInfo {
        bool enabled;
        uint256 minStakeNative;
        uint256 minStakeVault;
        TypeMintFee[] mintFees;
    }

    CountersUpgradeable.Counter private _tokenIdTracker;

    mapping(uint256 => uint256) public tokenType; // type of each NFT
    mapping(uint256 => uint256) public tokenBalanceOfStakedVault; // staked vault tokens in each NFT

    mapping(address => uint256) public ownerBalanceOfStakedVault; // staked vault tokens of each owner
    mapping(address => uint256) public ownerAverageBalanceOfStakedVaultLast;
    mapping(address => uint256) public ownerAverageBalanceOfStakedVaultLastAt;

    mapping(uint256 => TypeInfo) public typeInfo;

    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() initializer {}

    function initialize(string memory name, string memory symbol)
        public
        virtual
        initializer
    {
        __TheGreatWaveNFT_init(name, symbol);
    }

    /**
     * @dev Grants `DEFAULT_ADMIN_ROLE`, `MINTER_ROLE` and `PAUSER_ROLE` to the
     * account that deploys the contract.
     *
     * Token URIs will be autogenerated based on `baseURI` and their token IDs.
     * See {ERC721-tokenURI}.
     */
    function __TheGreatWaveNFT_init(string memory name, string memory symbol)
        internal
        initializer
    {
        __Context_init_unchained();
        __ERC165_init_unchained();
        __AccessControl_init_unchained();
        __AccessControlEnumerable_init_unchained();
        __ERC721_init_unchained(name, symbol);
        __ERC721Enumerable_init_unchained();
        __ERC721Burnable_init_unchained();
        __Pausable_init_unchained();
        __ERC721Pausable_init_unchained();

        __ERC1967Upgrade_init_unchained();
        __UUPSUpgradeable_init_unchained();

        __TheGreatWaveNFT_init_unchained();
    }

    function __TheGreatWaveNFT_init_unchained() internal initializer {
        _grantRole(DEFAULT_ADMIN_ROLE, ADMIN);

        _grantRole(MINTER_ROLE, ADMIN);
        // prettier-ignore
        _grantRole(MINTER_ROLE, address(0x4d9a23030B6C28fE2956F08497e0236E1B5f165c)); // TGW Treasury Gnosis Safe
        _grantRole(PAUSER_ROLE, ADMIN);
        // prettier-ignore
        _grantRole(PAUSER_ROLE, address(0x4d9a23030B6C28fE2956F08497e0236E1B5f165c)); // TGW Treasury Gnosis Safe

        IERC20Upgradeable(STAKE_VAULT_TOKEN).approve(
            STAKE_VAULT,
            type(uint256).max
        );
    }

    function _baseURI() internal view virtual override returns (string memory) {
        return "https://nft-data.thegreatwave.io/";
    }

    function tokenURI(uint256 tokenId)
        public
        view
        virtual
        override
        returns (string memory)
    {
        require(
            _exists(tokenId),
            "ERC721Metadata: URI query for nonexistent token"
        );

        if (tokenType[tokenId] == 0) {
            return string(abi.encodePacked(_baseURI(), tokenId.toString()));
        } else {
            return
                string(
                    abi.encodePacked(
                        _baseURI(),
                        tokenId.toString(),
                        "-",
                        tokenType[tokenId].toString()
                    )
                );
        }
    }

    /**
     * @dev Creates a new token for `to`. Its token ID will be automatically
     * assigned (and available on the emitted {IERC721-Transfer} event), and the token
     * URI autogenerated based on the base URI passed at construction.
     *
     * See {ERC721-_mint}.
     *
     * Requirements:
     *
     * - the caller must have the `MINTER_ROLE`.
     */
    function mint(address to) public virtual {
        mintWithTypeStake(to, 0, 0);
    }

    function mintWithTypeStake(
        address to,
        uint256 _type,
        uint256 amount
    ) public payable virtual returns (uint256 stakedVault) {
        TypeInfo memory _typeInfo = typeInfo[_type];

        if (!hasRole(MINTER_ROLE, _msgSender())) {
            require(_typeInfo.enabled, "!enabled");
        }

        uint256 valueLeft = msg.value;

        for (uint256 i = 0; i < _typeInfo.mintFees.length; i++) {
            require(valueLeft >= _typeInfo.mintFees[i].fee, "!mintFee");
            valueLeft -= _typeInfo.mintFees[i].fee;
            _typeInfo.mintFees[i].to.sendValue(_typeInfo.mintFees[i].fee);
        }

        uint256 beforeStakedVault = IERC20Upgradeable(STAKE_VAULT).balanceOf(address(this)); // prettier-ignore

        if (valueLeft > 0) {
            _valueToVault(valueLeft);
        }

        if (amount > 0) {
            IERC20Upgradeable(STAKE_VAULT).safeTransferFrom(
                _msgSender(),
                address(this),
                amount
            );
        }

        stakedVault = IERC20Upgradeable(STAKE_VAULT).balanceOf(address(this)) - beforeStakedVault; // prettier-ignore

        if (!hasRole(MINTER_ROLE, _msgSender())) {
            require(
                stakedVault >= _typeInfo.minStakeVault ||
                    valueLeft >= _typeInfo.minStakeNative,
                "!minStake"
            );
        }

        tokenBalanceOfStakedVault[_tokenIdTracker.current()] += stakedVault;
        tokenType[_tokenIdTracker.current()] = _type;

        _mint(to, _tokenIdTracker.current());
        _tokenIdTracker.increment();
    }

    function _valueToVault(uint256 value) internal {
        IBlpVault vault = IBlpVault(IBlpPool(STAKE_VAULT_TOKEN).getVault());
        bytes32 poolId = IBlpPool(STAKE_VAULT_TOKEN).getPoolId();
        (address[] memory assets, , ) = vault.getPoolTokens(poolId);

        uint256[] memory amountsIn = new uint256[](assets.length);
        uint256[] memory maxAmountsIn = new uint256[](assets.length);
        for (uint256 i = 0; i < assets.length; i++) {
            if (assets[i] == WBNB) {
                assets[i] = address(0);
                amountsIn[i] = value;
            }
            maxAmountsIn[i] = type(uint256).max;
        }

        uint256 beforeAmount = IERC20Upgradeable(STAKE_VAULT_TOKEN).balanceOf(address(this)); // prettier-ignore

        vault.joinPool{value: value}(
            poolId,
            address(this), // sender
            address(this), // recipient
            IBlpVault.JoinPoolRequest({
                assets: assets,
                maxAmountsIn: maxAmountsIn,
                userData: abi.encode(
                    IBlpPool.JoinKind.EXACT_TOKENS_IN_FOR_BPT_OUT,
                    amountsIn,
                    0 // minimumBPT
                ),
                fromInternalBalance: false
            })
        );

        IVault(STAKE_VAULT).deposit(
            IERC20Upgradeable(STAKE_VAULT_TOKEN).balanceOf(address(this)) -
                beforeAmount
        );
    }

    function setTypeInfo(uint256 _type, TypeInfo calldata _typeInfo)
        external
        onlyRole(MINTER_ROLE)
    {
        typeInfo[_type] = _typeInfo;
    }

    function typeMintFees(uint256 _type)
        external
        view
        returns (TypeMintFee[] memory)
    {
        return typeInfo[_type].mintFees;
    }

    /**
     * @dev Pauses all token transfers.
     *
     * See {ERC721Pausable} and {Pausable-_pause}.
     *
     * Requirements:
     *
     * - the caller must have the `PAUSER_ROLE`.
     */
    function pause() public virtual onlyRole(PAUSER_ROLE) {
        _pause();
    }

    /**
     * @dev Unpauses all token transfers.
     *
     * See {ERC721Pausable} and {Pausable-_unpause}.
     *
     * Requirements:
     *
     * - the caller must have the `PAUSER_ROLE`.
     */
    function unpause() public virtual onlyRole(PAUSER_ROLE) {
        _unpause();
    }

    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 tokenId
    )
        internal
        virtual
        override(
            ERC721Upgradeable,
            ERC721EnumerableUpgradeable,
            ERC721PausableUpgradeable
        )
    {
        super._beforeTokenTransfer(from, to, tokenId);

        if (from == address(0)) {
            // _stake() is called from mintToStake()
        } else if (from != to) {
            _updateOwnerAverageBalanceOfStakedVault(from);
            ownerBalanceOfStakedVault[from] -= tokenBalanceOfStakedVault[
                tokenId
            ];
        }
        if (to == address(0)) {
            _returnStakeToOwner(from, tokenId);
        } else if (to != from) {
            _updateOwnerAverageBalanceOfStakedVault(to);
            ownerBalanceOfStakedVault[to] += tokenBalanceOfStakedVault[tokenId];
        }
    }

    function _updateOwnerAverageBalanceOfStakedVault(address owner) private {
        if (ownerAverageBalanceOfStakedVaultLastAt[owner] >= block.timestamp)
            return;

        ownerAverageBalanceOfStakedVaultLast[
            owner
        ] = ownerAverageBalanceOfStakedVault(owner); // must get this before setting lastAt
        ownerAverageBalanceOfStakedVaultLastAt[owner] = block.timestamp;
    }

    function ownerAverageBalanceOfStakedVault(address owner)
        public
        view
        returns (uint256 balance)
    {
        uint256 lastWeight = ownerAverageBalanceOfStakedVaultLastAt[owner] >
            block.timestamp - AVERAGE_DURATION
            ? ownerAverageBalanceOfStakedVaultLastAt[owner] -
                (block.timestamp - AVERAGE_DURATION)
            : 0;
        balance =
            (ownerAverageBalanceOfStakedVaultLast[owner] *
                lastWeight +
                ownerBalanceOfStakedVault[owner] *
                (AVERAGE_DURATION - lastWeight)) /
            AVERAGE_DURATION;
    }

    function _returnStakeToOwner(address to, uint256 tokenId) private {
        uint256 amountStakedVault = tokenBalanceOfStakedVault[tokenId];
        tokenBalanceOfStakedVault[tokenId] = 0;

        IERC20Upgradeable(STAKE_VAULT).safeTransfer(to, amountStakedVault);
    }

    /**
     * @dev See {IERC165-supportsInterface}.
     */
    function supportsInterface(bytes4 interfaceId)
        public
        view
        virtual
        override(
            AccessControlEnumerableUpgradeable,
            ERC721Upgradeable,
            ERC721EnumerableUpgradeable
        )
        returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }

    function _authorizeUpgrade(address newImplementation)
        internal
        virtual
        override
        onlyRole(DEFAULT_ADMIN_ROLE)
    {}
}

// interface IWETH {
//     function deposit() external payable;

//     function withdraw(uint256) external;
// }

interface IBlpVault {
    function getPoolTokens(bytes32 poolId)
        external
        view
        returns (
            address[] memory tokens,
            uint256[] memory balances,
            uint256 lastChangeBlock
        );

    function joinPool(
        bytes32 poolId,
        address sender,
        address recipient,
        JoinPoolRequest memory request
    ) external payable;

    struct JoinPoolRequest {
        address[] assets;
        uint256[] maxAmountsIn;
        bytes userData;
        bool fromInternalBalance;
    }
}

interface IBlpPool {
    enum JoinKind {
        INIT,
        EXACT_TOKENS_IN_FOR_BPT_OUT,
        TOKEN_IN_FOR_EXACT_BPT_OUT,
        ALL_TOKENS_IN_FOR_EXACT_BPT_OUT
    }

    function getVault() external view returns (address);

    function getPoolId() external view returns (bytes32);
}

interface IVault {
    function deposit(uint256 _amount) external;

    function withdraw(uint256 _shares) external;
}
