// SPDX-License-Identifier: UNLICENSED

pragma solidity ^0.8.26;

// SPREADS Contracts
bytes32 constant SPREADS_VAULT_MANAGER_REPO_CONTRACT = keccak256("SPREADS_VAULT_MANAGER_REPO");
bytes32 constant SPREADS_VAULT_CALCULATOR_CONTRACT = keccak256("SPREADS_VAULT_CALCULATOR");
bytes32 constant SPREADS_VAULT_CONTRACT = keccak256("SPREADS_VAULT");
bytes32 constant SPREADS_VAULT_MANAGER_CONTRACT = keccak256("SPREADS_VAULT_MANAGER");
bytes32 constant STRATEGY_MANAGER = keccak256("STRATEGY_MANAGER");
bytes32 constant STRATEGY_MANAGER_REPO_CONTRACT = keccak256("STRATEGY_MANAGER_REPOSITORY");
bytes32 constant DERIVE_STRATEGY_REPO_CONTRACT = keccak256("DERIVE_STRATEGY_REPOSITORY");
bytes32 constant DERIVE_MULTISIG_CONTRACT = keccak256("DERIVE_MULTISIG");
bytes32 constant DERIVE_BRIDGE_REPO_CONTRACT = keccak256("DERIVE_BRIDGE_REPOSITORY");
bytes32 constant DERIVE_BRIDGE_CONTRACT = keccak256("DERIVE_BRIDGE");

// Additional contract constants for SPRVault
bytes32 constant VAULT_MANAGER_REPO_CONTRACT = keccak256("VAULT_MANAGER_REPO");
bytes32 constant SWAPPER_CONTRACT = keccak256("SWAPPER");
bytes32 constant TREASURY_CONTRACT = keccak256("TREASURY");
bytes32 constant STAKER_CONTRACT = keccak256("STAKER");
bytes32 constant WATERFALL_ACCOUNTING_CONTRACT = keccak256("WATERFALL_ACCOUNTING");

// Vault contracts
bytes32 constant YIELD_VAULT_CONTRACT = keccak256("YIELD_VAULT");
bytes32 constant AIRDROP_VAULT_CONTRACT = keccak256("AIRDROP_VAULT");
bytes32 constant SPR_VAULT_CONTRACT = keccak256("SPR_VAULT");
bytes32 constant VAULT_MANAGER_V2_CONTRACT = keccak256("VAULT_MANAGER_V2");
