// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;

interface IAggregator {
    /**
    * @notice Retrieves the latest answer of price from the contract
    * @return _latestAnswer The latest answer of price stored in the contract
    */
    function latestAnswer() external view returns (int256 _latestAnswer);

    /**
    * @notice Returns the number of decimals of the price feed generated by the contract
    * @return _decimals The number of decimals in which the price is provided
    */
    function decimals() external view returns (uint8 _decimals);
}