//SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

interface IVBuni {
    /**
     * @dev Creates a new token for `to`. Its token ID will be automatically
     * assigned (and available on the emitted {IERC721-Transfer} event), and the token
     * URI autogenerated based on the base URI passed at construction.
     *
     * See {ERC721-_mint}.
     *
     * Requirements:
     *
     * - the caller must have the `MINTER_ROLE`.
     */
    function mint(address to, uint256 poolId, uint256 buniAmount, uint256 vestedTimestamp) external;
}