/// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity ^0.8.0;

import "./libraries/AddArrayLib.sol";
import "solmate/utils/SafeTransferLib.sol";
import {FixedPointMathLib} from "solmate/utils/FixedPointMathLib.sol";

import "solmate/tokens/ERC20.sol";
import "solmate/mixins/ERC4626.sol";
import "solmate/utils/ReentrancyGuard.sol";

import "./interfaces/IVault.sol";
import "./interfaces/ITradeExecutor.sol";
import "./interfaces/IYieldExecutor.sol";

/// @title vault (Brahma Vault)
/// @author 0xAd1
/// @notice Minimal vault contract to support trades across different protocols.
contract Vault is IVault, ERC4626, ReentrancyGuard {
    using SafeTransferLib for ERC20;
    using FixedPointMathLib for uint256;

    /// @dev 1 BPS buffer for curve estimations
    uint256 public curveEstimateSlippage = 1e4;

    uint256 public assetBaseDecimalNormalization = 1e18;

    /// @dev yield generated by YieldExecutor during last epoch
    uint256 public lastEpochYield;

    /*///////////////////////////////////////////////////////////////
                                 CONSTANTS
    //////////////////////////////////////////////////////////////*/
    /// @dev The max basis points used as normalizing factor.
    uint256 public constant MAX_BPS = 10000;

    /*///////////////////////////////////////////////////////////////
                        GLOBAL MUTABLE STATE
    //////////////////////////////////////////////////////////////*/
    /// @notice performance fee collected by vault, during harvest
    /// @dev denomination in `MAX_BPS`
    uint256 public performanceFee;

    /*///////////////////////////////////////////////////////////////
                            MUTABLE ACCESS MODFIERS
    //////////////////////////////////////////////////////////////*/

    /// @notice boolean for enabling emergency mode to halt new withdrawal/deposits into vault.
    bool public emergencyMode;

    /// @notice keeper address to move funds between executors.
    address public override keeper;
    /// @notice Governance address to add/remove  executors.
    address public override governance;
    /// @notice Placeholder for new governance to be confirmed.
    address public pendingGovernance;

    constructor(
        address _asset,
        string memory _name,
        string memory _symbol,
        address _governance,
        address _keeper,
        uint256 _vaultDepositCap,
        uint256 _performanceFee
    ) ERC4626(ERC20(_asset), _name, _symbol) {
        governance = _governance;
        keeper = _keeper;
        vaultCapInAsset = _vaultDepositCap;
        performanceFee = _performanceFee;
    }

    /// @notice Combined assets of vault and yield executor and trade executor
    function totalAssets() public view override returns (uint256) {
        return totalLiquidAssets() + lastEpochYield;
    }

    /// @notice Combined assets of vault and yield executor, are solvent
    function totalLiquidAssets() public view returns (uint256) {
        return asset.balanceOf(address(this)) + totalYieldExecutorFunds();
    }

    /*//////////////////////////////////////////////////////////////
                          TE MAINTAINENCE LOGIC
    //////////////////////////////////////////////////////////////*/

    /// @notice Used to deposit asset into CurveYieldExecutor
    /// @param amountIn Amount of asset token to deposit
    /// @return lp LP tokens received after deposit
    function depositIntoYieldExecutor(uint256 amountIn)
        public
        returns (uint256 lp)
    {
        onlyGovernance();

        isValidAddress(address(yieldExecutor));
        asset.transfer(address(yieldExecutor), amountIn);
        lp = yieldExecutor.depositIntoExecutor(amountIn);
    }

    /// @notice Used to withdraw LP back into asset token from CurveYieldExecutor
    /// @param lp Amount of lp tokens to redeem back into asset tokens
    /// @return amountOut amount of asset tokens received
    function withdrawFromYieldExecutor(uint256 lp)
        public
        returns (uint256 amountOut)
    {
        onlyGovernance();

        isValidAddress(address(yieldExecutor));
        amountOut = yieldExecutor.withdrawfromExecutor(lp);
    }

    /// @notice event emitted when fees are collected
    /// @param fees fees collected in last harvest cycle
    event FeesCollected(uint256 fees);

    /// @param _claimYieldData bytes data to pass params to claimYield (Price of LDO)
    /// @param _withdrawData - reserved
    function harvest(
        bytes calldata _claimYieldData,
        bytes calldata _withdrawData,
        bool _shouldPlaceTrade
    ) public {
        onlyKeeper();
        isValidAddress(address(yieldExecutor));
        isValidAddress(address(tradeExecutor));

        uint256 prevAssetBal = asset.balanceOf(address(this));
        lastEpochYield = yieldExecutor.claimYield(_claimYieldData);
        uint256 baseYield = lastEpochYield;
        uint256 updatedAssetBal = asset.balanceOf(address(this));
        // Ensure baseYield reported correctly
        assert(updatedAssetBal - prevAssetBal == lastEpochYield);
        prevAssetBal = updatedAssetBal;
        uint256 boostedYield = tradeExecutor.initiateWithdraw(_withdrawData);
        updatedAssetBal = asset.balanceOf(address(this));
        // Ensure boostedYield reported correctly
        assert(updatedAssetBal - prevAssetBal == boostedYield);

        uint256 feeCollectedBase = 0;
        uint256 feeCollectedBoosted = 0;

        if (boostedYield > 0) {
            // Charge 1/2 Fee BPS from both yields
            feeCollectedBoosted +=
                (boostedYield * performanceFee) /
                MAX_BPS /
                2;
            feeCollectedBase += (baseYield * performanceFee) / MAX_BPS / 2;
        } else {
            // Charge 1 Fee BPS from base yeild
            feeCollectedBase += (baseYield * performanceFee) / MAX_BPS;
        }

        uint256 amountToCompound = 0;

        if (_shouldPlaceTrade) {
            // Send asset to tradeExecutor
            if (baseYield - feeCollectedBase > 0)
                asset.transfer(
                    address(tradeExecutor),
                    baseYield - feeCollectedBase
                );

            // Calculate amount to be compounded in yieldExecutor
            amountToCompound = boostedYield - feeCollectedBoosted;
        } else {
            // No trade to take, not sending anything to tradeExecutor
            // Calculate amount to be compounded in yieldExecutor
            amountToCompound =
                baseYield +
                boostedYield -
                feeCollectedBase -
                feeCollectedBoosted;
        }

        if (amountToCompound > 0) {
            asset.transfer(address(yieldExecutor), amountToCompound);
            yieldExecutor.depositIntoExecutor(amountToCompound);
        }

        if (feeCollectedBase + feeCollectedBoosted > 0) {
            // Send collected fee to governance
            asset.transfer(governance, feeCollectedBase + feeCollectedBoosted);
            emit FeesCollected(feeCollectedBase + feeCollectedBoosted);
        }
    }

    /*//////////////////////////////////////////////////////////////
                          ERC4626 OVERRIDES
    //////////////////////////////////////////////////////////////*/

    /// @notice Function to accept native MATIC in the vault
    /// @param receiver Address receiving shares of vault
    function deposit(address receiver)
        public
        payable
        nonReentrant
        returns (uint256 shares)
    {
        uint256 assets = msg.value;

        require((shares = previewDeposit(assets)) != 0, "ZERO_SHARES");

        require(
            address(asset) == 0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270,
            "NOT_NATIVE_ASSET"
        );
        require(assets > 0, "NO_ASSETS_RECEIVED");

        uint256 oldBal = asset.balanceOf(address(this));
        (bool success, ) = address(asset).call{value: assets}("");
        require(success, "WRAP_UNSUCCESS");
        uint256 newBal = asset.balanceOf(address(this));

        require(newBal - oldBal == assets, "WRAP_UNSUCCESSFULL");

        _mint(receiver, shares);

        emit Deposit(msg.sender, receiver, assets, shares);

        afterDeposit(assets, shares);
    }

    /// @dev override IERC4626
    function previewDeposit(uint256 assets)
        public
        view
        override
        returns (uint256)
    {
        uint256 lpMinted = yieldExecutor.previewAddLiquidity(assets);
        lpMinted =
            lpMinted -
            (lpMinted * curveEstimateSlippage) /
            assetBaseDecimalNormalization;
        uint256 lpValueInAssets = yieldExecutor.lpValueInAsset(lpMinted);
        return convertToShares(lpValueInAssets);
    }

    /// @dev override IERC4626
    function previewMint(uint256 shares)
        public
        pure
        override
        returns (uint256 assets)
    {
        revert("CURVE_AMM_ESTIMATION_NOT_SUPPORTED");
    }

    /// @dev override IERC4626
    function previewWithdraw(uint256 assets)
        public
        pure
        override
        returns (uint256 shares)
    {
        revert("CURVE_AMM_ESTIMATION_NOT_SUPPORTED");
    }

    /// @dev override IERC4626
    function previewRedeem(uint256 shares)
        public
        view
        override
        returns (uint256 totalAssetsOwed)
    {
        uint256 assetBalance = asset.balanceOf(address(this)) +
            asset.balanceOf(address(yieldExecutor));
        uint256 assetOwed = (assetBalance * shares) / totalSupply;
        uint256 lpBalance = yieldExecutor.totalLPTokens();
        uint256 lpOwed = (lpBalance * shares) / totalSupply;
        uint256 lpValueOwed = yieldExecutor.previewWithdrawLiquidity(lpOwed);
        lpValueOwed =
            lpValueOwed -
            (lpValueOwed * curveEstimateSlippage) /
            assetBaseDecimalNormalization;
        totalAssetsOwed = assetOwed + lpValueOwed;
    }

    /*//////////////////////////////////////////////////////////////
                          INTERNAL HOOKS LOGIC
    //////////////////////////////////////////////////////////////*/

    /// @dev internal accountuing and funds management logic before issuing withdrawal
    function beforeWithdraw(uint256 assets, uint256 shares) internal override {
        require(!emergencyMode, "EMERGENCY");

        uint256 vaultAssetBalance = asset.balanceOf(address(this));
        uint256 yieldExecutorAssetBalance = asset.balanceOf(
            address(yieldExecutor)
        );
        uint256 assetBalance = vaultAssetBalance + yieldExecutorAssetBalance;
        uint256 assetOwed = (assetBalance * shares) / totalSupply;
        uint256 lpBalance = yieldExecutor.totalLPTokens();
        uint256 lpOwed = (lpBalance * shares) / totalSupply;

        if (assetOwed > vaultAssetBalance) {
            asset.safeTransferFrom(
                address(yieldExecutor),
                address(this),
                assetOwed - vaultAssetBalance
            );
        }

        yieldExecutor.withdrawfromExecutor(lpOwed);

        assert(asset.balanceOf(address(this)) >= assets);
    }

    /// @dev internal accountuing and funds management logic after accepting deposit
    function afterDeposit(uint256 assets, uint256 shares) internal override {
        require(!emergencyMode, "EMERGENCY");

        isValidAddress(address(yieldExecutor));
        require(totalAssets() <= vaultCapInAsset, "VAULT_CAP_EXCEEDED");
        asset.transfer(address(yieldExecutor), assets);
        yieldExecutor.depositIntoExecutor(assets);
    }

    /*///////////////////////////////////////////////////////////////
                    EXECUTOR ADDITION/REMOVAL LOGIC
    //////////////////////////////////////////////////////////////*/

    /// @notice list of yield executors connected to vault.
    IYieldExecutor public yieldExecutor;

    /// @notice list of trade executors connected to vault.
    ITradeExecutor public tradeExecutor;

    /// @notice Emitted when executor is added to vault.
    /// @param executor The address of added executor.
    event YieldExecutorAdded(address indexed executor);

    /// @notice Emitted when executor is added to vault.
    /// @param executor The address of added executor.
    event TradeExecutorAdded(address indexed executor);

    /// @notice Yield Executor setter
    /// @param _yieldExecutor new yield executor address
    function setYieldExecutor(address _yieldExecutor) public {
        onlyGovernance();
        isValidAddress(_yieldExecutor);
        require(
            ITradeExecutor(_yieldExecutor).vault() == address(this),
            "INVALID_VAULT"
        );
        require(
            asset.allowance(_yieldExecutor, address(this)) > 0,
            "NO_ALLOWANCE"
        );
        yieldExecutor = IYieldExecutor(_yieldExecutor);
        emit YieldExecutorAdded(_yieldExecutor);
    }

    /// @notice Trade Executor setter
    /// @param _tradeExecutor new trade executor address
    function setTradeExecutor(address _tradeExecutor) public {
        onlyGovernance();
        isValidAddress(_tradeExecutor);
        require(
            ITradeExecutor(_tradeExecutor).vault() == address(this),
            "INVALID_VAULT"
        );
        require(
            asset.allowance(_tradeExecutor, address(this)) > 0,
            "NO_ALLOWANCE"
        );
        tradeExecutor = ITradeExecutor(_tradeExecutor);
        emit TradeExecutorAdded(_tradeExecutor);
    }

    function totalYieldExecutorFunds() public view returns (uint256 posValue) {
        (posValue, ) = yieldExecutor.totalFunds();
        return posValue;
    }

    // function totalTradeExecutorFunds() public view returns (uint256 posValue) {
    //     (posValue, ) = tradeExecutor.totalFunds();
    //     return posValue;
    // }

    /*//////////////////////////////////////////////////////////////
                     DEPOSIT/WITHDRAWAL LIMIT LOGIC
    //////////////////////////////////////////////////////////////*/

    /// @notice Tracking max deposit limit of vault
    uint256 public vaultCapInAsset;

    function maxDeposit(address) public view override returns (uint256) {
        return vaultCapInAsset - totalAssets();
    }

    function maxMint(address) public view override returns (uint256) {
        return convertToShares(maxDeposit(address(0)));
    }

    /*///////////////////////////////////////////////////////////////
                    GOVERNANCE ACTIONS
    //////////////////////////////////////////////////////////////*/

    /// @notice Changes the vault deposit cap
    /// @param _newVaultCap New vault deposit cap
    function setVaultCap(uint256 _newVaultCap) public {
        onlyGovernance();
        vaultCapInAsset = _newVaultCap;
    }

    /// @notice Nominates new governance address.
    /// @dev  Governance will only be changed if the new governance accepts it. It will be pending till then.
    /// @param _governance The address of new governance.
    function setGovernance(address _governance) public {
        onlyGovernance();
        pendingGovernance = _governance;
    }

    /// @notice Emitted when governance is updated.
    /// @param oldGovernance The address of the current governance.
    /// @param newGovernance The address of new governance.
    event UpdatedGovernance(
        address indexed oldGovernance,
        address indexed newGovernance
    );

    /// @notice The nomine of new governance address proposed by `setGovernance` function can accept the governance.
    /// @dev  This can only be called by address of pendingGovernance.
    function acceptGovernance() public {
        require(msg.sender == pendingGovernance, "INVALID_ADDRESS");
        emit UpdatedGovernance(governance, pendingGovernance);
        governance = pendingGovernance;
    }

    /// @notice Emitted when keeper is updated.
    /// @param oldKeeper The address of the old keeper.
    /// @param newKeeper The address of the new keeper.
    event UpdatedKeeper(address indexed oldKeeper, address indexed newKeeper);

    /// @notice Sets new keeper address.
    /// @dev  This can only be called by governance.
    /// @param _keeper The address of new keeper.
    function setKeeper(address _keeper) public {
        onlyGovernance();
        emit UpdatedKeeper(keeper, _keeper);
        keeper = _keeper;
    }

    /// @notice Emitted when emergencyMode status is updated.
    /// @param emergencyMode boolean indicating state of emergency.
    event EmergencyModeStatus(bool emergencyMode);

    /// @notice sets emergencyMode.
    /// @dev  This can only be called by governance.
    /// @param _emergencyMode if true, vault will be in emergency mode.
    function setEmergencyMode(bool _emergencyMode) public {
        onlyGovernance();
        emergencyMode = _emergencyMode;
        emit EmergencyModeStatus(_emergencyMode);
    }

    /// @notice Removes invalid tokens from the vault.
    /// @dev  This is used as fail safe to remove want tokens from the vault during emergency mode
    /// can be called by anyone to send funds to governance.
    /// @param _token The address of token to be removed.
    function sweep(address _token) public {
        isEmergencyMode();
        onlyGovernance();
        ERC20(_token).safeTransfer(
            governance,
            ERC20(_token).balanceOf(address(this))
        );
    }

    /// @notice Changes the curve estimation slippage offset
    /// @param _estimateSlippage new curve estimate slippage
    function setCurveEstimateSlippage(uint256 _estimateSlippage) public {
        onlyGovernance();
        curveEstimateSlippage = _estimateSlippage;
    }

    /// @notice Emitted when performance fee is updated
    /// @param prevFee fee before update
    /// @param curFee current fee
    event UpdatedPerformanceFee(uint256 prevFee, uint256 curFee);

    /// @notice Governance function to set performance fee
    /// @param newPerformanceFee the new performance fee to be updated
    function setPerformanceFee(uint256 newPerformanceFee) public {
        onlyGovernance();
        require(newPerformanceFee <= MAX_BPS / 2, "FEE_TOO_HIGH");

        emit UpdatedPerformanceFee(performanceFee, newPerformanceFee);
        performanceFee = newPerformanceFee;
    }

    /*///////////////////////////////////////////////////////////////
                    ACCESS MODIFERS
    //////////////////////////////////////////////////////////////*/

    /// @dev Checks if emergency mode is enabled.
    function isEmergencyMode() public view {
        require(emergencyMode, "EMERGENCY_MODE");
    }

    /// @dev Checks if the sender is the governance.
    function onlyGovernance() internal view {
        require(msg.sender == governance, "ONLY_GOV");
    }

    /// @dev Checks if the sender is the keeper.
    function onlyKeeper() internal view {
        require(msg.sender == keeper, "ONLY_KEEPER");
    }

    /// @dev Checks if the address is valid.
    function isValidAddress(address _addr) internal pure {
        require(_addr != address(0), "NULL_ADDRESS");
    }
}
