// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

/// @title  IFactory
/// @notice Permissionless factory for (Token, BondingCurve) pairs. The owner can rotate
///         the live {CurveConfig}; rotations affect future deploys only — every curve is
///         frozen against its own snapshot at construction.
interface IFactory {
    /* -------------------------------------------------------------------------- */
    /*                                   CONFIG                                   */
    /* -------------------------------------------------------------------------- */

    /// @notice Parameters copied into every new {IBondingCurve} at deploy.
    struct CurveConfig {
        uint256 virtualTokenReserves;
        uint256 virtualEthReserves;
        uint256 curveSupply;
        uint256 migrationSupply;
        uint256 graduationEthTarget;
        /// @notice Protocol share of the graduation event, in wei.
        uint256 graduationFeeWei;
        /// @notice Creator bonus paid at graduation, in wei.
        uint256 creatorGraduationRewardWei;
        uint96 protocolFeeBps;
        uint96 creatorFeeBps;
        address protocolFeeRecipient;
        address migrator;
        /// @notice Duration of the creator-only first-buy window, in seconds. Applied at
        ///         deploy when a launch opts in via `creatorFirstBuy = true`. Hard-capped
        ///         via `MAX_CREATOR_WINDOW`. Setting this to 0 forbids the window entirely.
        uint64 creatorFirstBuyWindowSec;
    }

    /* -------------------------------------------------------------------------- */
    /*                                   EVENTS                                   */
    /* -------------------------------------------------------------------------- */

    event TokenCreated(
        address indexed token, address indexed creator, address indexed bondingCurve, string name, string symbol
    );
    event ConfigUpdated(CurveConfig newConfig);
    event CreationFeeUpdated(uint256 newFee);

    /* -------------------------------------------------------------------------- */
    /*                                  ACTIONS                                   */
    /* -------------------------------------------------------------------------- */

    /// @notice Deploy a new (Token, BondingCurve) pair at salt-chosen addresses.
    /// @param  name             ERC20 name; length ∈ [1, 32], no ASCII control characters.
    /// @param  symbol           ERC20 symbol; length ∈ [1, 10], no ASCII control characters.
    /// @param  creator          Address entitled to the creator share of trade fees.
    /// @param  metadataURI      ERC-7572 metadata URI. Permanently immutable on the token.
    /// @param  cashbackMode     Per-launch, irrevocable: zeros the creator share, traders
    ///                          pay only the protocol share.
    /// @param  creatorFirstBuy  Per-launch, irrevocable: arms the creator-only first-buy
    ///                          window of duration `CurveConfig.creatorFirstBuyWindowSec`.
    /// @param  tokenSalt        CREATE2 salt for the token (mine off-chain for vanity).
    /// @param  curveSalt        CREATE2 salt for the bonding curve.
    function createToken(
        string calldata name,
        string calldata symbol,
        address creator,
        string calldata metadataURI,
        bool cashbackMode,
        bool creatorFirstBuy,
        bytes32 tokenSalt,
        bytes32 curveSalt
    ) external payable returns (address token, address curve);

    /// @notice Replace the live {CurveConfig}. Owner-only. Affects future deploys only.
    function setConfig(CurveConfig calldata cfg) external;

    /// @notice Replace the ETH fee charged on {createToken}. Owner-only; hard-capped.
    function setCreationFee(uint256 wei_) external;

    /* -------------------------------------------------------------------------- */
    /*                                   VIEWS                                    */
    /* -------------------------------------------------------------------------- */

    /// @notice Struct-returning accessor for the live config (more ergonomic for external
    ///         contracts than the autogenerated tuple getter).
    function getCurrentConfig() external view returns (CurveConfig memory);

    /// @notice ETH amount {createToken} callers must forward as `msg.value`.
    function creationFeeWei() external view returns (uint256);

    /// @notice Predict the addresses {createToken} would deploy to under the current config.
    /// @dev    If the config changes between prediction and deploy, the CURVE address moves
    ///         (its init code embeds the config). The TOKEN address is unaffected.
    function predictAddresses(
        string calldata name,
        string calldata symbol,
        address creator,
        bytes32 tokenSalt,
        bytes32 curveSalt
    ) external view returns (address token, address curve);

    /// @notice True iff `curve` was deployed by this factory. Used by the fee hook and
    ///         migrator to gate privileged callbacks.
    function isBondingCurve(address curve) external view returns (bool);

    /// @notice The bonding curve the factory is currently CREATE2-deploying. Non-zero only
    ///         between the two CREATE2 calls inside {createToken}.
    function pendingCurve() external view returns (address);

    /// @notice The ERC-7572 metadata URI the factory is currently stamping into a new token.
    ///         Non-empty only during the Token CREATE2 inside {createToken}.
    function pendingURI() external view returns (string memory);
}
