// SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;

// AutomationCompatible.sol imports the functions from both ./AutomationBase.sol and
// ./interfaces/AutomationCompatibleInterface.sol
import '@chainlink/contracts/src/v0.8/AutomationCompatible.sol';
import { IVodkaVault } from '../interfaces/IVodkaVault.sol';
import '@openzeppelin/contracts/access/Ownable.sol';

contract VaultkaKeeper is AutomationCompatibleInterface, Ownable {
    event VodkaVaultAddressUpdated(address vodkaVault);

    IVodkaVault internal vodkaVault;

    constructor(address _vodkaVault) {
        vodkaVault = IVodkaVault(_vodkaVault);
    }

    function setVodkaVault(address _vodkaVault) external onlyOwner {
        vodkaVault = IVodkaVault(_vodkaVault);
        emit VodkaVaultAddressUpdated(_vodkaVault);
    }

    function checkUpkeep(
        bytes calldata /* checkData */
    )
        external
        view
        override
        returns (
            bool upkeepNeeded,
            bytes memory /* performData */
        )
    {
        //@note calling isVaildRebalance
        upkeepNeeded = vodkaVault.isValidRebalance();

        return (upkeepNeeded, '0x0');

        // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered.
    }

    function performUpkeep(
        bytes calldata /* performData */
    ) external override {
        //We highly recommend revalidating the upkeep in the performUpkeep function
        //if isVaildRebalance is true
        if (vodkaVault.isValidRebalance()) {
            //rebalance();
            vodkaVault.rebalance();
        }
        // We don't use the performData in this example. The performData is generated by the Automation Node's call to your checkUpkeep function
    }
}
