// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.28;

interface IQuote {
    struct WidgetFee {
        address feeRecipient;
        uint256 feeRate;
    }

    struct RFQTQuote {
        /*//////////////////////////////////////////////////////////////////////////
                            RFQ QUOTE ONLY FIELDS
        //////////////////////////////////////////////////////////////////////////*/
        /// @notice RFQ pool address or external swap router address
        address pool;
        /// @notice market maker
        address signer;
        /// @notice The recipient of the buyerToken at the end of the trade.
        address recipient;
        /// @notice The token that the trader sells.
        address sellerToken;
        /// @notice The token that the trader buys.
        address buyerToken;
        /// @notice The max amount of sellerToken sold.
        uint256 sellerTokenAmount;
        /// @notice The amount of buyerToken bought when sellerTokenAmount is sold.
        uint256 buyerTokenAmount;
        /// @notice The Unix timestamp (in seconds) when the quote expires.
        /// @dev This gets checked against block.timestamp.
        uint256 deadlineTimestamp;
        /// @notice Nonces are used to protect against replay.
        uint256 nonce;
        /// @notice Unique identifier for the quote.
        /// @dev Generated off-chain via a distributed UUID generator.
        bytes16 quoteId;
        /// @dev  false if this quote is for the 1st hop of a multi-hop or a single-hop, in which case msg.sender is the payer.
        ///       true if this quote is for 2nd or later hop of a multi-hop, in which case router is the payer.
        bool multiHop;
        /// @notice Signature provided by the market maker (EIP-191).
        bytes signature;
        /// @notice Widget fee information
        WidgetFee widgetFee;
        /// @notice Widget fee signature
        bytes widgetFeeSignature;
        /*//////////////////////////////////////////////////////////////////////////
                            EXTERNAL SWAP ONLY FIELDS
        //////////////////////////////////////////////////////////////////////////*/

        /// @notice External swap calldata, different external swap router have different calldata
        bytes externalSwapCalldata;
        /// @notice Minimum amount out for external swap (AMM)
        uint256 amountOutMinimum;
    }

    struct PermitQuote {
        /// @notice The address of the user who want to the swap
        address swapper;
        /// @notice The address of the market maker providing liquidity
        address marketMaker;
        /// @notice The token being sold by the swapper
        address tokenIn;
        /// @notice The token being bought by the swapper
        address tokenOut;
        /// @notice The maximum amount of tokenIn that can be sold
        uint256 amountIn;
        /// @notice The maximum amount of tokenOut that will be received by the swapper
        uint256 amountOut;
        /// @notice The recipient of the tokenOut
        address recipient;
        /// @notice RFQ pool address
        address pool;
        /// @notice Nonces are used to protect against replay.
        uint256 nonce;
        /// @notice market maker's auto-sign orderbook deadline
        uint256 deadline;
        /// @notice Signature signed by off-chain
        bytes signature;
        /// @notice Signature generated by market maker for their pushed auto-sign orderbook
        bytes orderBookSig;
        /// @notice Digest generated by market maker for their pushed auto-sign orderbook
        bytes32 orderBookDigest;
        /// @notice Widget fee info
        WidgetFee widgetFee;
    }
}
