//SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.0;

// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// GENERATED CODE - do not edit manually!!
// This code was generated by the Synthetix router project and deployed with Cannon.
// Learn more: https://usecannon.com/learn/guides/router
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------

contract USDRouter {
    error UnknownSelector(bytes4 sel);

    address immutable private _ROUTER_ADDRESS;

    constructor() {
        _ROUTER_ADDRESS = address(this);

        bytes4[] memory selectors;
        selectors = new bytes4[](8);
        selectors[0] = 0x79ba5097;
        selectors[1] = 0xaaf10f42;
        selectors[2] = 0x1627540c;
        selectors[3] = 0x53a47bb7;
        selectors[4] = 0x8da5cb5b;
        selectors[5] = 0x718fe928;
        selectors[6] = 0xc7f62cda;
        selectors[7] = 0x3659cfe6;
        _facets().push(Facet(_INITIAL_MODULE_BUNDLE, selectors));
        selectors = new bytes4[](4);
        selectors[0] = 0x60988e09;
        selectors[1] = 0x2d22bef9;
        selectors[2] = 0xc6f79537;
        selectors[3] = 0xd245d983;
        _facets().push(Facet(_ASSOCIATED_SYSTEMS_MODULE, selectors));
        selectors = new bytes4[](18);
        selectors[0] = 0xdd62ed3e;
        selectors[1] = 0x095ea7b3;
        selectors[2] = 0x70a08231;
        selectors[3] = 0x42966c68;
        selectors[4] = 0x9dc29fac;
        selectors[5] = 0xaaa15fd1;
        selectors[6] = 0x313ce567;
        selectors[7] = 0xa457c2d7;
        selectors[8] = 0x39509351;
        selectors[9] = 0x1624f6c6;
        selectors[10] = 0x392e53cd;
        selectors[11] = 0x40c10f19;
        selectors[12] = 0x06fdde03;
        selectors[13] = 0xda46098c;
        selectors[14] = 0x95d89b41;
        selectors[15] = 0x18160ddd;
        selectors[16] = 0xa9059cbb;
        selectors[17] = 0x23b872dd;
        _facets().push(Facet(_USDTOKEN_MODULE, selectors));

        _emitDiamondCutEvent();
    }

    address private constant _INITIAL_MODULE_BUNDLE = 0x828EED723cAF0A8F822249231266E38dF614923C;
    address private constant _ASSOCIATED_SYSTEMS_MODULE = 0xF297E891d7f92b842B17fcfa3e70Da29aCaEc6De;
    address private constant _USDTOKEN_MODULE = 0xDaf89F5a0125E7eBA36cd01B5A3C40b76F697B91;

    fallback(bytes calldata cd) external payable returns (bytes memory) {
        // Lookup table: Function selector => implementation contract
        bytes4 sig4 = msg.sig;
        address implementation;

        assembly {
            let sig32 := shr(224, sig4)

            function findImplementation(sig) -> result {
                if lt(sig,0x70a08231) {
                    if lt(sig,0x3659cfe6) {
                        switch sig
                        case 0x06fdde03 { result := _USDTOKEN_MODULE } // USDTokenModule.name()
                        case 0x095ea7b3 { result := _USDTOKEN_MODULE } // USDTokenModule.approve()
                        case 0x1624f6c6 { result := _USDTOKEN_MODULE } // USDTokenModule.initialize()
                        case 0x1627540c { result := _INITIAL_MODULE_BUNDLE } // InitialModuleBundle.nominateNewOwner()
                        case 0x18160ddd { result := _USDTOKEN_MODULE } // USDTokenModule.totalSupply()
                        case 0x23b872dd { result := _USDTOKEN_MODULE } // USDTokenModule.transferFrom()
                        case 0x2d22bef9 { result := _ASSOCIATED_SYSTEMS_MODULE } // AssociatedSystemsModule.initOrUpgradeNft()
                        case 0x313ce567 { result := _USDTOKEN_MODULE } // USDTokenModule.decimals()
                        leave
                    }
                    switch sig
                    case 0x3659cfe6 { result := _INITIAL_MODULE_BUNDLE } // InitialModuleBundle.upgradeTo()
                    case 0x392e53cd { result := _USDTOKEN_MODULE } // USDTokenModule.isInitialized()
                    case 0x39509351 { result := _USDTOKEN_MODULE } // USDTokenModule.increaseAllowance()
                    case 0x40c10f19 { result := _USDTOKEN_MODULE } // USDTokenModule.mint()
                    case 0x42966c68 { result := _USDTOKEN_MODULE } // USDTokenModule.burn()
                    case 0x53a47bb7 { result := _INITIAL_MODULE_BUNDLE } // InitialModuleBundle.nominatedOwner()
                    case 0x60988e09 { result := _ASSOCIATED_SYSTEMS_MODULE } // AssociatedSystemsModule.getAssociatedSystem()
                    leave
                }
                if lt(sig,0xaaa15fd1) {
                    switch sig
                    case 0x70a08231 { result := _USDTOKEN_MODULE } // USDTokenModule.balanceOf()
                    case 0x718fe928 { result := _INITIAL_MODULE_BUNDLE } // InitialModuleBundle.renounceNomination()
                    case 0x79ba5097 { result := _INITIAL_MODULE_BUNDLE } // InitialModuleBundle.acceptOwnership()
                    case 0x8da5cb5b { result := _INITIAL_MODULE_BUNDLE } // InitialModuleBundle.owner()
                    case 0x95d89b41 { result := _USDTOKEN_MODULE } // USDTokenModule.symbol()
                    case 0x9dc29fac { result := _USDTOKEN_MODULE } // USDTokenModule.burn()
                    case 0xa457c2d7 { result := _USDTOKEN_MODULE } // USDTokenModule.decreaseAllowance()
                    case 0xa9059cbb { result := _USDTOKEN_MODULE } // USDTokenModule.transfer()
                    leave
                }
                switch sig
                case 0xaaa15fd1 { result := _USDTOKEN_MODULE } // USDTokenModule.burnWithAllowance()
                case 0xaaf10f42 { result := _INITIAL_MODULE_BUNDLE } // InitialModuleBundle.getImplementation()
                case 0xc6f79537 { result := _ASSOCIATED_SYSTEMS_MODULE } // AssociatedSystemsModule.initOrUpgradeToken()
                case 0xc7f62cda { result := _INITIAL_MODULE_BUNDLE } // InitialModuleBundle.simulateUpgradeTo()
                case 0xd245d983 { result := _ASSOCIATED_SYSTEMS_MODULE } // AssociatedSystemsModule.registerUnmanagedSystem()
                case 0xda46098c { result := _USDTOKEN_MODULE } // USDTokenModule.setAllowance()
                case 0xdd62ed3e { result := _USDTOKEN_MODULE } // USDTokenModule.allowance()
                leave
            }

            implementation := findImplementation(sig32)
        }

        if (implementation == address(0)) {
            // It's possible this contract is being called through yet another proxy. Call the router in order to make sure we have right data.
            if (address(this) != _ROUTER_ADDRESS) {
                (bool success, bytes memory result) = _ROUTER_ADDRESS.call(cd);
                if (success) {
                    return result;
                } else {
                    revert UnknownSelector(sig4);
                }
            } else {
                // Check for diamond compat call
                if (sig4 == 0x7a0ed627) {
                    return abi.encode(_facets());
                }
                if (sig4 == 0xadfca15e) {
                    (address facet) = abi.decode(cd[4:], (address));
                    return abi.encode(_facetFunctionSelectors(facet));
                }
                if (sig4 == 0x52ef6b2c) {
                    return abi.encode(_facetAddresses());
                }
                if (sig4 == 0xcdffacc6) {
                    (bytes4 sig) = abi.decode(cd[4:], (bytes4));
                    return abi.encode(_facetAddress(sig));
                }
                if (sig4 == 0x8cce96cb) {
                    return abi.encode(_emitDiamondCutEvent());
                }
            }
            revert UnknownSelector(sig4);
        }

        // Delegatecall to the implementation contract
        assembly {
            calldatacopy(0, 0, calldatasize())

            let result := delegatecall(gas(), implementation, 0, calldatasize(), 0, 0)
            returndatacopy(0, 0, returndatasize())

            switch result
            case 0 {
                revert(0, returndatasize())
            }
            default {
                return(0, returndatasize())
            }
        }
    }

    struct Facet {
        address facetAddress;
        bytes4[] functionSelectors;
    }

    enum FacetCutAction {Add, Replace, Remove}
    // Add=0, Replace=1, Remove=2

    struct FacetCut {
        address facetAddress;
        FacetCutAction action;
        bytes4[] functionSelectors;
    }

    /// @notice Gets all facet addresses and their four byte function selectors.
    /// @return facets_ Facet
    function _facets() internal pure returns (Facet[] storage facets_) {
        bytes32 s = keccak256("Router.USDRouter");
        assembly {
            facets_.slot := s
        }
    }

    /// @notice Gets all the function selectors supported by a specific facet.
    /// @param _facet The facet address.
    /// @return facetFunctionSelectors_
    function _facetFunctionSelectors(address _facet) internal view returns (bytes4[] memory facetFunctionSelectors_) {
        Facet[] storage facets = _facets();
        for (uint256 i = 0;i < facets.length;i++) {
            if (facets[i].facetAddress == _facet) {
                return facets[i].functionSelectors;
            }
        }
    }

    /// @notice Get all the facet addresses used by a diamond.
    /// @return facetAddresses_
    function _facetAddresses() internal pure returns (address[] memory facetAddresses_) {
        facetAddresses_ = new address[](3);
        facetAddresses_[0] = _INITIAL_MODULE_BUNDLE;
        facetAddresses_[1] = _ASSOCIATED_SYSTEMS_MODULE;
        facetAddresses_[2] = _USDTOKEN_MODULE;
    }

    /// @notice Gets the facet that supports the given selector.
    /// @dev If facet is not found return address(0).
    /// @param _functionSelector The function selector.
    /// @return facetAddress_ The facet address.
    function _facetAddress(bytes4 _functionSelector) internal view returns (address facetAddress_) {
        Facet[] storage facets = _facets();
        for (uint256 i = 0;i < facets.length;i++) {
            for (uint256 j = 0;j < facets[i].functionSelectors.length;j++) {
                if (facets[i].functionSelectors[j] == _functionSelector) {
                    return facets[i].facetAddress;
                }
            }
        }
    }

    event DiamondCut(FacetCut[] _diamondCut, address _init, bytes _calldata);

    /// @notice Emits the cut events that would be emitted if this was actually a diamond
    function _emitDiamondCutEvent() internal returns (bool) {
        FacetCut[] memory cuts = new FacetCut[](3);
        cuts[0] = FacetCut(_INITIAL_MODULE_BUNDLE, FacetCutAction.Add, _facetFunctionSelectors(_INITIAL_MODULE_BUNDLE));
        cuts[1] = FacetCut(_ASSOCIATED_SYSTEMS_MODULE, FacetCutAction.Add, _facetFunctionSelectors(_ASSOCIATED_SYSTEMS_MODULE));
        cuts[2] = FacetCut(_USDTOKEN_MODULE, FacetCutAction.Add, _facetFunctionSelectors(_USDTOKEN_MODULE));
        emit DiamondCut(cuts, address(0), new bytes(0));
        return true;
    }
}
