// SPDX-License-Identifier: MIT
pragma solidity 0.8.13;


import "@openzeppelin/contracts/utils/math/SafeMath.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";

import '../interfaces/Pairs/IPairInfo.sol';
interface IFeeVault {
    function claimFees() external returns(uint256 claimed0, uint256 claimed1);
}


contract GaugeSimple is ReentrancyGuard, Ownable {
    using SafeMath for uint256;
    using SafeERC20 for IERC20;

    bool public emergency;

    
    uint256 public constant DURATION = 1 weeks;
    uint256 internal _totalSupply;

    address public DISTRIBUTION;
    address public feeVault;
    address[] public rewardTokens;

    mapping(address => uint256) internal _periodFinish;
    mapping(address => uint256) internal _rewardRate;
    mapping(address => uint256) internal _lastUpdateTime;
    mapping(address => uint256) internal _rewardPerTokenStored;
    mapping(address => bool) public isRewardToken;
    mapping(address => mapping(address => uint256)) internal _userRewardPerTokenPaid;
    mapping(address => mapping(address => uint256)) public rewards;
    mapping(address => uint256) public _balances;

    IERC20 public TOKEN;

    string public version = "3.0.1";
    
    event RewardAdded(address indexed token, uint256 reward);
    event Deposit(address indexed user, uint256 amount);
    event Withdraw(address indexed user, uint256 amount);
    event Harvest(address indexed user, address indexed token, uint256 reward);
    event ClaimFees(address indexed from, uint claimed0, uint claimed1);



    modifier onlyDistribution() {
        require(msg.sender == DISTRIBUTION, "!distributor");
        _;
    }

    modifier isNotEmergency() {
        require(emergency == false);
        _;
    }

    /// @notice Deploy contract
    /// @param _rewardtokens    tokens to add as incentive
    /// @param _token           underlying token of the gauge
    /// @param _distribution    who distribute rewards
    /// @param _feeVault        where to get fees generated by the underlying token
    constructor(address[] memory _rewardtokens,address _token,address _distribution, address _feeVault) {

        // add tokens
        for(uint i = 0; i < _rewardtokens.length; i++){
            if(_rewardtokens[i] != address(0)){
                isRewardToken[_rewardtokens[i]] = true;     
                rewardTokens.push(_rewardtokens[i]);        
            }
        }

        TOKEN = IERC20(_token);                 // underlying (LP)

        DISTRIBUTION = _distribution;           // distro address 

        feeVault = _feeVault;                   // where to claim fees

        emergency = false;                       // emergency flag

    }


    /* -----------------------------------------------------------------------------
    --------------------------------------------------------------------------------
    --------------------------------------------------------------------------------
                                    ONLY OWNER
    --------------------------------------------------------------------------------
    --------------------------------------------------------------------------------
    ----------------------------------------------------------------------------- */

    ///@notice set distribution address (should be GaugeProxyL2)
    function setDistribution(address _distribution) external onlyOwner {
        require(_distribution != address(0), "zero addr");
        require(_distribution != DISTRIBUTION, "same addr");
        DISTRIBUTION = _distribution;
    }
  
    ///@notice set feeVault address
    function setFeeVault(address _feeVault) external onlyOwner {
        require(_feeVault != address(0), "zero addr");
        require(_feeVault != feeVault, "same addr");
        feeVault = _feeVault;
    }

     function activateEmergencyMode() external onlyOwner {
        require(emergency == false);
        emergency = true;
    }

    function stopEmergencyMode() external onlyOwner {
        require(emergency == false);
        emergency = false;
    }

    function addRewardToken(address _token) external onlyOwner {
        require(!isRewardToken[_token], 'Gauge: isRewardToken');
        require(_token != address(0), 'Gauge: address 0');
        isRewardToken[_token] = true;
        rewardTokens.push(_token);

    }

    function removeRewardToken(address _token) external onlyOwner {
        require(isRewardToken[_token], 'Gauge: !isRewardToken');
        uint256 len = rewardTokensLength();
        for(uint i = 0; i < len; i++){
            if(rewardTokens[i] == _token){
                _clearTokenInfo(_token, i);
                break;
            }
        }
    }

    function _clearTokenInfo(address _token, uint256 i) internal {
        rewardTokens[i] = rewardTokens[rewardTokens.length -1];
        rewardTokens.pop();
        isRewardToken[_token] = false;
    }


    /* -----------------------------------------------------------------------------
    --------------------------------------------------------------------------------
    --------------------------------------------------------------------------------
                                    VIEW FUNCTIONS
    --------------------------------------------------------------------------------
    --------------------------------------------------------------------------------
    ----------------------------------------------------------------------------- */
    
    function rewardTokensLength() public view returns(uint256){
        return rewardTokens.length;
    }

    ///@notice total supply held
    function totalSupply() public view returns (uint256) {
        return _totalSupply;
    }

    ///@notice balance of a user
    function balanceOf(address account) external view returns (uint256) {
        return _balances[account];
    }

    function rewardRate(address _token) external view returns(uint256){
        return _rewardRate[_token];
    }

    ///@notice  reward for a single token
    function rewardPerToken(address _token) public view returns(uint256) {
        return _rewardPerToken(_token);
    }


    ///@notice get total reward for the duration
    function rewardForDuration(address _token) external view returns (uint256) {
        return _rewardRate[_token] * DURATION;
    }

    ///@notice see earned rewards for user 
    function earned(address _account, address _token) public view returns (uint256) {
        return _earned(_account, _token);
    }

    function earnedAll(address _account) public view returns(uint256[] memory amounts) {
        uint256 i = 0;
        uint256 len = rewardTokens.length;
        address _token;
        amounts = new uint256[](len);
        for(i;i<len;i++){
            _token = rewardTokens[i];
            amounts[i] = _earned(_account, _token);
        }
    }
    

 

    function periodFinish(address _token) external view returns (uint256) {
        return _periodFinish[_token];
    }



    /* -----------------------------------------------------------------------------
    --------------------------------------------------------------------------------
    --------------------------------------------------------------------------------
                                    USER INTERACTION
    --------------------------------------------------------------------------------
    --------------------------------------------------------------------------------
    ----------------------------------------------------------------------------- */


    ///@notice deposit all TOKEN of msg.sender
    function depositAll() external {
        _deposit(TOKEN.balanceOf(msg.sender), msg.sender);
    }

    ///@notice deposit amount TOKEN
    function deposit(uint256 amount) external {
        _deposit(amount, msg.sender);
    }

    ///@notice deposit internal
    function _deposit(uint256 amount, address account) internal nonReentrant isNotEmergency {
        require(amount > 0, "deposit(Gauge): cannot stake 0");
        _updateAllRewards(account);

        _balances[account] = _balances[account].add(amount);
        _totalSupply = _totalSupply.add(amount);

        TOKEN.safeTransferFrom(account, address(this), amount);

        emit Deposit(account, amount);
    }

    ///@notice withdraw all TOKEN and harvest rewardToken
    function withdrawAllAndHarvest() external {
        _withdraw(_balances[msg.sender]);
        getReward();
    }

    ///@notice withdraw all token
    function withdrawAll() external {
        _withdraw(_balances[msg.sender]);
    }

    ///@notice withdraw a certain amount of TOKEN
    function withdraw(uint256 amount) external {
        _withdraw(amount);
    }

    ///@notice withdraw internal
    function _withdraw(uint256 amount) internal nonReentrant isNotEmergency {
        require(amount > 0, "Cannot withdraw 0");
        require(_totalSupply.sub(amount) >= 0, "supply < 0");
        require(_balances[msg.sender] > 0, "no balances");
        _updateAllRewards(msg.sender);

        _totalSupply = _totalSupply.sub(amount);
        _balances[msg.sender] = _balances[msg.sender].sub(amount);


        TOKEN.safeTransfer(msg.sender, amount);

        emit Withdraw(msg.sender, amount);
    }

    /// @notice Withdraw all user balance if emergency is active
    function emergencyWithdraw() external nonReentrant {
        require(emergency);
        require(_balances[msg.sender] > 0, "no balances");

        uint256 _amount = _balances[msg.sender];
        _totalSupply = _totalSupply.sub(_amount);
        _balances[msg.sender] = 0;

        TOKEN.safeTransfer(msg.sender, _amount);
        emit Withdraw(msg.sender, _amount);
    }
    
    
    /// @notice Withdraw 'amount' user balance if emergency is active
    function emergencyWithdrawAmount(uint256 _amount) external nonReentrant {
        require(emergency);
        require(_balances[msg.sender] >= _amount, "no balances");

        _totalSupply = _totalSupply.sub(_amount);
        _balances[msg.sender] -= _amount;
        TOKEN.safeTransfer(msg.sender, _amount);
        emit Withdraw(msg.sender, _amount);
    }


    ///@notice User harvest function
    function getReward() public nonReentrant {
        _getReward(msg.sender);
    }

    function _getReward(address _account) internal {
        _updateAllRewards(_account);
        uint256 i = 0;
        uint256 len = rewardTokens.length;
        address _token;
        for(i; i < len; i++){
            _token = rewardTokens[i];
            uint256 reward = rewards[_account][_token];
            if (reward > 0) {
                rewards[_account][_token] = 0;
                IERC20(_token).safeTransfer(_account, reward);
                emit Harvest(_account, _token, reward);
            }
        }
    }


    /* -----------------------------------------------------------------------------
    --------------------------------------------------------------------------------
                                    INTERNAL
    --------------------------------------------------------------------------------
    ----------------------------------------------------------------------------- */


    function _updateAllRewards(address _account) internal {
        uint256 i = 0;
        uint256 len = rewardTokens.length;
        address _token;
        for(i; i < len; i++) {
            _token = rewardTokens[i];
            _updateReward(_account, _token);
        }
    }

    function _updateReward(address _account, address _token) internal {
        uint256 _rPTS = rewardPerToken(_token);
        _rewardPerTokenStored[_token] = _rPTS;
        _lastUpdateTime[_token] = _lastTimeRewardApplicable(_token);
        if (_account != address(0)) {
            rewards[_account][_token] = _earned(_account, _token);
            _userRewardPerTokenPaid[_account][_token] = _rPTS;
        }
    }


    function _earned(address _account, address _token) internal view returns(uint256) {
        uint256 _newRewards = _balances[_account] * (_rewardPerToken(_token) - _userRewardPerTokenPaid[_account][_token]) / 1e18;
        return  _newRewards + rewards[_account][_token]; 
    }

    function _rewardPerToken(address _token) internal view returns (uint256) {
        uint256 _rewPTS = _rewardPerTokenStored[_token];
        if (_totalSupply == 0) {
            return _rewPTS;
        } else {
            return _rewPTS + (_lastTimeRewardApplicable(_token) - _lastUpdateTime[_token]) * _rewardRate[_token] * 1e18 / _totalSupply;
        }
    }

    /// @notice last time reward
    function _lastTimeRewardApplicable(address _token) internal view returns (uint256) {
        return _min(block.timestamp, _periodFinish[_token]);
    }

    /// @notice find min amount between two inputs 
    function _min(uint a, uint b) internal pure returns (uint) {
        return a < b ? a : b;
    }

    /* -----------------------------------------------------------------------------
    --------------------------------------------------------------------------------
                                    DISTRIBUTION
    --------------------------------------------------------------------------------
    ----------------------------------------------------------------------------- */


    /// @dev Receive rewards from distribution only
    function notifyRewardAmount(address _token, uint _amount) external nonReentrant isNotEmergency onlyDistribution {
        _notifyRewardAmount(_token, _amount, false);
    }

    /// @notice Save new incentives
    /// @param _token       token to receive
    /// @param _amount      amount to receive
    /// @param isInternal   if true then is called from claimFees() else DISTRIBUTION
    function _notifyRewardAmount(address _token, uint _amount, bool isInternal) internal {
        _updateReward(address(0), _token);
        require(isRewardToken[_token], 'Gauge: _token !allowed');
        if(!isInternal) IERC20(_token).safeTransferFrom(msg.sender, address(this), _amount);

        uint256 _periodEnd = _periodFinish[_token];

        if (block.timestamp >= _periodEnd) {
            _rewardRate[_token] = _amount.div(DURATION);
        } else {
            uint256 _rewRate = _rewardRate[_token]; 
            uint256 leftover = (_periodEnd - block.timestamp) * _rewRate;
            _rewardRate[_token] = _amount.add(leftover).div(DURATION);
        }

        // Ensure the provided reward amount is not more than the balance in the contract.
        // This keeps the reward rate in the right range, preventing overflows due to
        // very high values of rewardRate in the earned and rewardsPerToken functions;
        // Reward + leftover must be less than 2^256 / 10^18 to avoid overflow.
        uint256 balance = IERC20(_token).balanceOf(address(this));
        require(_rewardRate[_token] <= balance.div(DURATION), "Gauge: Provided reward too high");

        _lastUpdateTime[_token] = block.timestamp;
        _periodFinish[_token] = block.timestamp.add(DURATION);

        emit RewardAdded(_token, _amount);
    }


    function claimFees() external nonReentrant returns (uint claimed0, uint claimed1) {
        return _claimFees();
    }

     function _claimFees() internal returns (uint _claimed0, uint _claimed1) {

        address _token = address(TOKEN);
        (_claimed0, _claimed1) = IFeeVault(feeVault).claimFees();

        (address _token0) = IPairInfo(_token).token0();
        (address _token1) = IPairInfo(_token).token1();
        if (_claimed0  > 0) {
            _notifyRewardAmount(_token0, _claimed0, true);
        } 

        if (_claimed1  > 0) {
            _notifyRewardAmount(_token1, _claimed1, true);
        } 

        emit ClaimFees(msg.sender, _claimed0, _claimed1);
        
    }

}
