// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

import { IERC20Metadata } from "@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol";

import { IUsdn } from "./IUsdn.sol";

/**
 * @title USDnr Token Interface
 * @notice The USDnr token is a vault containing USDN token, allowing users to deposit and withdraw USDN at a 1:1 ratio.
 */
interface IUsdnr is IERC20Metadata {
    /**
     * @notice The yield generated by the underlying USDN tokens has been withdrawn.
     * @param recipient The address that received the yield.
     * @param amount The amount of yield withdrawn.
     */
    event USDnrYieldWithdrawn(address recipient, uint256 amount);

    /**
     * @notice The yield recipient has been updated.
     * @param newYieldRecipient The new address of the yield recipient.
     */
    event USDnrYieldRecipientUpdated(address newYieldRecipient);

    /// @notice The amount provided is zero.
    error USDnrZeroAmount();

    /// @notice The recipient address is the zero address.
    error USDnrZeroRecipient();

    /// @notice There is no yield available to withdraw.
    error USDnrNoYield();

    /**
     * @notice The minimum amount of USDN that must remain in the contract to ensure that all USDnr tokens
     * are fully backed.
     * @dev Due to rounding to the nearest unit of the USDN token, each time a user deposits their tokens, the contract
     * may receive up to 0.5 wei less than expected. This reserve ensures that the last user can withdraw their full
     * balance. The reserve is fixed at 1 gwei.
     * @return reserve_ The fixed amount of USDN, used as a reserve.
     */
    function RESERVE() external pure returns (uint256 reserve_);

    /**
     * @notice Returns the address of the USDN token contract.
     * @return usdn_ The address of the USDN token contract.
     */
    function USDN() external view returns (IUsdn usdn_);

    /**
     * @notice Returns the address that will receive the yield when {withdrawYield} is called.
     * @return yieldRecipient_ The address of the yield recipient.
     */
    function getYieldRecipient() external view returns (address yieldRecipient_);

    /**
     * @notice Sets a new address to receive the yield when {withdrawYield} is called.
     * @dev Can only be called by the owner.
     * @param newYieldRecipient The address of the new yield recipient.
     */
    function setYieldRecipient(address newYieldRecipient) external;

    /**
     * @notice Deposits USDN to mint USDnr at a 1:1 ratio.
     *  @dev When approving USDN, use the `convertToTokensRoundUp` of the user shares, as we always round up when
     * deducting from a token transfer allowance.
     * @param usdnAmount The amount of USDN to deposit.
     * @param recipient The address to receive the USDnr tokens.
     */
    function deposit(uint256 usdnAmount, address recipient) external;

    /**
     * @notice Previews the amount of USDnr that would be minted for depositing a given amount of USDN shares.
     * @param usdnSharesAmount The amount of USDN shares to deposit.
     * @return mintedAmount_ The amount of USDnr that would be minted.
     */
    function previewDepositShares(uint256 usdnSharesAmount) external view returns (uint256 mintedAmount_);

    /**
     * @notice Deposits USDN shares to mint USDnr.
     * @dev The shares must represent at least 1 wei of USDN token. The conversion ratio is 1:1 with the USDN amount.
     * @param usdnSharesAmount The amount of USDN shares to deposit.
     * @param recipient The address to receive the USDnr tokens.
     * @return mintedAmount_ The amount of USDN tokens that were deposited, and the amount of USDnr tokens minted.
     */
    function depositShares(uint256 usdnSharesAmount, address recipient) external returns (uint256 mintedAmount_);

    /**
     * @notice Withdraws USDN by giving USDnr at a 1:1 ratio.
     * @param usdnAmount The amount of USDN to withdraw.
     * @param recipient The address to receive the USDN tokens.
     */
    function withdraw(uint256 usdnAmount, address recipient) external;

    /**
     * @notice Withdraws the yield generated by the underlying USDN tokens to the `_yieldRecipient`.
     * @dev The yield is the difference between the USDN balance of the contract and the total supply of USDnr. To
     * calculate the balance we use `USDN.sharesOf(address(this)) / USDN.divisor()` to round down, ensuring that all
     * USDnr tokens are always fully backed by USDN.
     */
    function withdrawYield() external;
}
