// SPDX-License-Identifier: GPL-3.0-only

pragma solidity ^0.8.0;

interface IAlgebraV2Adapter {
    /// @dev Output amount is lower than expected amount out
    error InsufficientAmount();

    /// @dev Thrown when the caller is not the pool address
    error NotPoolAddress();

    /// @dev Event emitted when the quoter is set
    event QuoterSet(address quoter);

    /// @dev Parameters struct for a quote
    struct QParams {
        address tokenIn;
        address tokenOut;
        int256 amount;
        bool exactIn;
    }

    /// @notice Returns an address for a given key and index combination
    /// @param key The keccak256 key generated by encoding tokenA and tokenB
    /// @param index The index of the array to retrieve the address from
    function deployers(bytes32 key, uint256 index) external view returns (address);

    /// @notice Returns list of whitelisted deployers for a given tokenA/tokenB combination
    /// @param key Keccack256 hash of tokenA and tokenB encoded addresses
    function getDeployers(bytes32 key) external view returns (address[] memory);

    /// @notice Whitelists a custom deployer for a given tokenA and tokenB combination
    /// @param deployer Address of deployer of pool
    /// @param tokenA The address of tokenA
    /// @param tokenB The address of tokenB
    function addCustomDeployer(address deployer, address tokenA, address tokenB) external;

    /// @notice Removes a whitelisted custom deployer for a given tokenA and tokenB combination
    /// @param tokenA The address of tokenA
    /// @param tokenB The address of tokenB
    /// @param index Index in the list of whitelisted deployers for the given pool
    function removeCustomDeployer(address tokenA, address tokenB, uint256 index) external;

    /// @notice Swaps tokens using a specific deployer's pool
    /// @param amountIn Amount of input tokens
    /// @param amountOut Minimum amount of output tokens expected
    /// @param tokenIn Address of input token
    /// @param tokenOut Address of output token
    /// @param to Address to receive output tokens
    /// @param deployer Address of the deployer for custom pool (address(0) for factory pool)
    function swap(
        uint256 amountIn,
        uint256 amountOut,
        address tokenIn,
        address tokenOut,
        address to,
        address deployer
    ) external;

    /// @notice Queries the adapter for swap quote and returns the deployer info
    /// @param amount Input amount (if exactIn) or output amount (if !exactIn)
    /// @param tokenIn Address of the input token
    /// @param tokenOut Address of the output token
    /// @param exactIn True for exact input quote, false for exact output quote
    /// @return quoteAmount The output amount (if exactIn) or required input amount (if !exactIn)
    /// @return recipient The address that should receive tokens for this adapter
    /// @return deployer The deployer address for custom pool (address(0) for factory pool)
    function queryWithDeployer(uint256 amount, address tokenIn, address tokenOut, bool exactIn)
        external
        view
        returns (uint256 quoteAmount, address recipient, address deployer);
}
