//SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.0;

// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// GENERATED CODE - do not edit manually!!
// This code was generated by the Synthetix router project and deployed with Cannon.
// Learn more: https://usecannon.com/learn/guides/router
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------

contract CoreRouter {
    error UnknownSelector(bytes4 sel);

    address immutable private _ROUTER_ADDRESS;

    constructor() {
        _ROUTER_ADDRESS = address(this);

        bytes4[] memory selectors;
        selectors = new bytes4[](8);
        selectors[0] = 0x79ba5097;
        selectors[1] = 0xaaf10f42;
        selectors[2] = 0x1627540c;
        selectors[3] = 0x53a47bb7;
        selectors[4] = 0x8da5cb5b;
        selectors[5] = 0x718fe928;
        selectors[6] = 0xc7f62cda;
        selectors[7] = 0x3659cfe6;
        _facets().push(Facet(_INITIAL_MODULE_BUNDLE, selectors));
        selectors = new bytes4[](10);
        selectors[0] = 0xa0778144;
        selectors[1] = 0xed429cf7;
        selectors[2] = 0x40a399ef;
        selectors[3] = 0xe12c8160;
        selectors[4] = 0xbcae3ea0;
        selectors[5] = 0xcf635949;
        selectors[6] = 0xb7746b59;
        selectors[7] = 0x715cb7d2;
        selectors[8] = 0x7d632bd2;
        selectors[9] = 0x5e52ad6e;
        _facets().push(Facet(_FEATURE_FLAG_MODULE, selectors));
        selectors = new bytes4[](12);
        selectors[0] = 0x9dca362f;
        selectors[1] = 0xcadb09a5;
        selectors[2] = 0x1b5dccdb;
        selectors[3] = 0xbf60c31d;
        selectors[4] = 0xa796fecd;
        selectors[5] = 0xa148bf10;
        selectors[6] = 0x00cd9ef3;
        selectors[7] = 0x8d34166b;
        selectors[8] = 0x1213d453;
        selectors[9] = 0x7dec8b55;
        selectors[10] = 0x47c1c561;
        selectors[11] = 0xa7627288;
        _facets().push(Facet(_ACCOUNT_MODULE, selectors));
        selectors = new bytes4[](1);
        selectors[0] = 0x11aa282d;
        _facets().push(Facet(_ASSOCIATE_DEBT_MODULE, selectors));
        selectors = new bytes4[](4);
        selectors[0] = 0x60988e09;
        selectors[1] = 0x2d22bef9;
        selectors[2] = 0xc6f79537;
        selectors[3] = 0xd245d983;
        _facets().push(Facet(_ASSOCIATED_SYSTEMS_MODULE, selectors));
        selectors = new bytes4[](1);
        selectors[0] = 0x85572ffb;
        _facets().push(Facet(_CCIP_RECEIVER_MODULE, selectors));
        selectors = new bytes4[](7);
        selectors[0] = 0x198f0aa1;
        selectors[1] = 0x0bae9893;
        selectors[2] = 0x83802968;
        selectors[3] = 0x927482ff;
        selectors[4] = 0xef45148e;
        selectors[5] = 0xaa8c6369;
        selectors[6] = 0x95997c51;
        _facets().push(Facet(_COLLATERAL_MODULE, selectors));
        selectors = new bytes4[](4);
        selectors[0] = 0x644cb0f3;
        selectors[1] = 0xdc0b3f52;
        selectors[2] = 0x75bf2444;
        selectors[3] = 0x51a40994;
        _facets().push(Facet(_COLLATERAL_CONFIGURATION_MODULE, selectors));
        selectors = new bytes4[](1);
        selectors[0] = 0x340824d7;
        _facets().push(Facet(_CROSS_CHAIN_USDMODULE, selectors));
        selectors = new bytes4[](2);
        selectors[0] = 0xd3264e43;
        selectors[1] = 0xdf16a074;
        _facets().push(Facet(_ISSUE_USDMODULE, selectors));
        selectors = new bytes4[](4);
        selectors[0] = 0x2fa7bb65;
        selectors[1] = 0x2a5354d2;
        selectors[2] = 0x3e033a06;
        selectors[3] = 0x7d8a4140;
        _facets().push(Facet(_LIQUIDATION_MODULE, selectors));
        selectors = new bytes4[](6);
        selectors[0] = 0xdbdea94c;
        selectors[1] = 0xa4e6306b;
        selectors[2] = 0xc2b0cf41;
        selectors[3] = 0xd4f88381;
        selectors[4] = 0x12e1c673;
        selectors[5] = 0xa3aa8b51;
        _facets().push(Facet(_MARKET_COLLATERAL_MODULE, selectors));
        selectors = new bytes4[](23);
        selectors[0] = 0x10b0cf76;
        selectors[1] = 0xa0c12269;
        selectors[2] = 0xd24437f1;
        selectors[3] = 0x741a5d3f;
        selectors[4] = 0x150834a3;
        selectors[5] = 0x95909ba3;
        selectors[6] = 0xdfb83437;
        selectors[7] = 0x5424901b;
        selectors[8] = 0x85d99ebc;
        selectors[9] = 0x25eeea4b;
        selectors[10] = 0x7a75c869;
        selectors[11] = 0xbe0b8e6f;
        selectors[12] = 0x86e3b1cf;
        selectors[13] = 0xbaa2a264;
        selectors[14] = 0x84f29b6d;
        selectors[15] = 0xb01ceccd;
        selectors[16] = 0x21f1d9e5;
        selectors[17] = 0x1eb60770;
        selectors[18] = 0x07003f0a;
        selectors[19] = 0xa79b9ec9;
        selectors[20] = 0x1d90e392;
        selectors[21] = 0x6fd5bdce;
        selectors[22] = 0x140a7cfe;
        _facets().push(Facet(_MARKET_MANAGER_MODULE, selectors));
        selectors = new bytes4[](5);
        selectors[0] = 0xb790a1ae;
        selectors[1] = 0x48741626;
        selectors[2] = 0x3b390b57;
        selectors[3] = 0xe1b440d0;
        selectors[4] = 0xe7098c0c;
        _facets().push(Facet(_POOL_CONFIGURATION_MODULE, selectors));
        selectors = new bytes4[](21);
        selectors[0] = 0xc707a39f;
        selectors[1] = 0xcaab529b;
        selectors[2] = 0xfd85c1f8;
        selectors[3] = 0x9851af01;
        selectors[4] = 0xc77e51f6;
        selectors[5] = 0xc4d2aad3;
        selectors[6] = 0xefecf137;
        selectors[7] = 0x2ad71386;
        selectors[8] = 0xf86e6f91;
        selectors[9] = 0xbbdd7c5a;
        selectors[10] = 0x9b20dc89;
        selectors[11] = 0x6141f7a2;
        selectors[12] = 0x183231d7;
        selectors[13] = 0xca5bed77;
        selectors[14] = 0x7cc14a92;
        selectors[15] = 0x1f1b33b9;
        selectors[16] = 0x34078a01;
        selectors[17] = 0x5a4aabb1;
        selectors[18] = 0x4c6568b1;
        selectors[19] = 0x5d8c8844;
        selectors[20] = 0x11e72a43;
        _facets().push(Facet(_POOL_MODULE, selectors));
        selectors = new bytes4[](10);
        selectors[0] = 0x50f2f49b;
        selectors[1] = 0x460d2049;
        selectors[2] = 0x5a7ff7c5;
        selectors[3] = 0x49cd69ec;
        selectors[4] = 0xeaeacda3;
        selectors[5] = 0xc4b3410e;
        selectors[6] = 0x0dd2395a;
        selectors[7] = 0x170c1351;
        selectors[8] = 0x2685f42b;
        selectors[9] = 0x645657d8;
        _facets().push(Facet(_REWARDS_MANAGER_MODULE, selectors));
        selectors = new bytes4[](10);
        selectors[0] = 0x10d52805;
        selectors[1] = 0xa5d49393;
        selectors[2] = 0x6dd5b69d;
        selectors[3] = 0xf896503a;
        selectors[4] = 0xf92bb8c9;
        selectors[5] = 0xce1b815f;
        selectors[6] = 0x572b6c05;
        selectors[7] = 0xd1fd27b3;
        selectors[8] = 0x830e23b5;
        selectors[9] = 0x01ffc9a7;
        _facets().push(Facet(_UTILS_MODULE, selectors));
        selectors = new bytes4[](10);
        selectors[0] = 0x7b0532a4;
        selectors[1] = 0xfd93aa76;
        selectors[2] = 0xf544d66e;
        selectors[3] = 0x33cc422b;
        selectors[4] = 0xdc0a5384;
        selectors[5] = 0x3593bbd2;
        selectors[6] = 0x078145a8;
        selectors[7] = 0x60248c55;
        selectors[8] = 0x2fb8ff24;
        selectors[9] = 0xb7e3e68c;
        _facets().push(Facet(_VAULT_MODULE, selectors));

        _emitDiamondCutEvent();
    }

    address private constant _INITIAL_MODULE_BUNDLE = 0x828EED723cAF0A8F822249231266E38dF614923C;
    address private constant _FEATURE_FLAG_MODULE = 0x5559A519FdC9F210a96075aD969F56FD2DC48a58;
    address private constant _ACCOUNT_MODULE = 0x435358ABcfd3E85563Ae88665fBB2033C1a003EC;
    address private constant _ASSOCIATE_DEBT_MODULE = 0xEf35b98d2e2BBA6717fBF12130f741E573dDE7Cb;
    address private constant _ASSOCIATED_SYSTEMS_MODULE = 0xF297E891d7f92b842B17fcfa3e70Da29aCaEc6De;
    address private constant _CCIP_RECEIVER_MODULE = 0xD15fdC12Cc41D5083b194f6c2F6E9Be71677c099;
    address private constant _COLLATERAL_MODULE = 0xEB30f42da93c20e921247a56Bbf09859A2626D26;
    address private constant _COLLATERAL_CONFIGURATION_MODULE = 0x5d94EE64C5e698DBEeB95a3D0d5A0D4B8B8Bc647;
    address private constant _CROSS_CHAIN_USDMODULE = 0xD237F237356e456214Ad5b57e0A962d632F1F3C5;
    address private constant _ISSUE_USDMODULE = 0x3a6061c7642f1df8503E6Eb8A599D7d8B4317524;
    address private constant _LIQUIDATION_MODULE = 0xe1ba4Af6e3B76aF365A391D9d1ed75CAECbDC965;
    address private constant _MARKET_COLLATERAL_MODULE = 0xbB46F9FB7BB2c73C9486148bFc70BCDF6A2bEaaF;
    address private constant _MARKET_MANAGER_MODULE = 0x0CB4bf413d8eabe0F7892eAaE9f69F3fa31094dC;
    address private constant _POOL_CONFIGURATION_MODULE = 0x3093cbba626e60E4164975f5b15dD1c0D03BF927;
    address private constant _POOL_MODULE = 0x600f30C285c11f1a94f282A933B24Fb5fDa13Cf3;
    address private constant _REWARDS_MANAGER_MODULE = 0xCB3707D3Fd182679d1a61ed5f30d94bFf532E144;
    address private constant _UTILS_MODULE = 0x750714EC1357042e2102BC25E20e5359C27168d3;
    address private constant _VAULT_MODULE = 0xA49Ef964876B802454Cd2Ec11aC6A23f7Ca01158;

    fallback(bytes calldata cd) external payable returns (bytes memory) {
        // Lookup table: Function selector => implementation contract
        bytes4 sig4 = msg.sig;
        address implementation;

        assembly {
            let sig32 := shr(224, sig4)

            function findImplementation(sig) -> result {
                if lt(sig,0x830e23b5) {
                    if lt(sig,0x3b390b57) {
                        if lt(sig,0x1b5dccdb) {
                            if lt(sig,0x11e72a43) {
                                switch sig
                                case 0x00cd9ef3 { result := _ACCOUNT_MODULE } // AccountModule.grantPermission()
                                case 0x01ffc9a7 { result := _UTILS_MODULE } // UtilsModule.supportsInterface()
                                case 0x07003f0a { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.isMarketCapacityLocked()
                                case 0x078145a8 { result := _VAULT_MODULE } // VaultModule.getVaultCollateral()
                                case 0x0bae9893 { result := _COLLATERAL_MODULE } // CollateralModule.createLock()
                                case 0x0dd2395a { result := _REWARDS_MANAGER_MODULE } // RewardsManagerModule.getRewardRate()
                                case 0x10b0cf76 { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.depositMarketUsd()
                                case 0x10d52805 { result := _UTILS_MODULE } // UtilsModule.configureChainlinkCrossChain()
                                case 0x11aa282d { result := _ASSOCIATE_DEBT_MODULE } // AssociateDebtModule.associateDebt()
                                leave
                            }
                            switch sig
                            case 0x11e72a43 { result := _POOL_MODULE } // PoolModule.setPoolName()
                            case 0x1213d453 { result := _ACCOUNT_MODULE } // AccountModule.isAuthorized()
                            case 0x12e1c673 { result := _MARKET_COLLATERAL_MODULE } // MarketCollateralModule.getMaximumMarketCollateral()
                            case 0x140a7cfe { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.withdrawMarketUsd()
                            case 0x150834a3 { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.getMarketCollateral()
                            case 0x1627540c { result := _INITIAL_MODULE_BUNDLE } // InitialModuleBundle.nominateNewOwner()
                            case 0x170c1351 { result := _REWARDS_MANAGER_MODULE } // RewardsManagerModule.registerRewardsDistributor()
                            case 0x183231d7 { result := _POOL_MODULE } // PoolModule.rebalancePool()
                            case 0x198f0aa1 { result := _COLLATERAL_MODULE } // CollateralModule.cleanExpiredLocks()
                            leave
                        }
                        if lt(sig,0x2d22bef9) {
                            switch sig
                            case 0x1b5dccdb { result := _ACCOUNT_MODULE } // AccountModule.getAccountLastInteraction()
                            case 0x1d90e392 { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.setMarketMinDelegateTime()
                            case 0x1eb60770 { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.getWithdrawableMarketUsd()
                            case 0x1f1b33b9 { result := _POOL_MODULE } // PoolModule.revokePoolNomination()
                            case 0x21f1d9e5 { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.getUsdToken()
                            case 0x25eeea4b { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.getMarketPoolDebtDistribution()
                            case 0x2685f42b { result := _REWARDS_MANAGER_MODULE } // RewardsManagerModule.removeRewardsDistributor()
                            case 0x2a5354d2 { result := _LIQUIDATION_MODULE } // LiquidationModule.isVaultLiquidatable()
                            case 0x2ad71386 { result := _POOL_MODULE } // PoolModule.getPoolDebtPerShare()
                            leave
                        }
                        switch sig
                        case 0x2d22bef9 { result := _ASSOCIATED_SYSTEMS_MODULE } // AssociatedSystemsModule.initOrUpgradeNft()
                        case 0x2fa7bb65 { result := _LIQUIDATION_MODULE } // LiquidationModule.isPositionLiquidatable()
                        case 0x2fb8ff24 { result := _VAULT_MODULE } // VaultModule.getVaultDebt()
                        case 0x33cc422b { result := _VAULT_MODULE } // VaultModule.getPositionCollateral()
                        case 0x34078a01 { result := _POOL_MODULE } // PoolModule.setMinLiquidityRatio()
                        case 0x340824d7 { result := _CROSS_CHAIN_USDMODULE } // CrossChainUSDModule.transferCrossChain()
                        case 0x3593bbd2 { result := _VAULT_MODULE } // VaultModule.getPositionDebt()
                        case 0x3659cfe6 { result := _INITIAL_MODULE_BUNDLE } // InitialModuleBundle.upgradeTo()
                        leave
                    }
                    if lt(sig,0x60988e09) {
                        if lt(sig,0x51a40994) {
                            switch sig
                            case 0x3b390b57 { result := _POOL_CONFIGURATION_MODULE } // PoolConfigurationModule.getPreferredPool()
                            case 0x3e033a06 { result := _LIQUIDATION_MODULE } // LiquidationModule.liquidate()
                            case 0x40a399ef { result := _FEATURE_FLAG_MODULE } // FeatureFlagModule.getFeatureFlagAllowAll()
                            case 0x460d2049 { result := _REWARDS_MANAGER_MODULE } // RewardsManagerModule.claimRewards()
                            case 0x47c1c561 { result := _ACCOUNT_MODULE } // AccountModule.renouncePermission()
                            case 0x48741626 { result := _POOL_CONFIGURATION_MODULE } // PoolConfigurationModule.getApprovedPools()
                            case 0x49cd69ec { result := _REWARDS_MANAGER_MODULE } // RewardsManagerModule.distributeRewardsByOwner()
                            case 0x4c6568b1 { result := _POOL_MODULE } // PoolModule.setPoolCollateralDisabledByDefault()
                            case 0x50f2f49b { result := _REWARDS_MANAGER_MODULE } // RewardsManagerModule.claimPoolRewards()
                            leave
                        }
                        switch sig
                        case 0x51a40994 { result := _COLLATERAL_CONFIGURATION_MODULE } // CollateralConfigurationModule.getCollateralPrice()
                        case 0x53a47bb7 { result := _INITIAL_MODULE_BUNDLE } // InitialModuleBundle.nominatedOwner()
                        case 0x5424901b { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.getMarketMinDelegateTime()
                        case 0x572b6c05 { result := _UTILS_MODULE } // UtilsModule.isTrustedForwarder()
                        case 0x5a4aabb1 { result := _POOL_MODULE } // PoolModule.setPoolCollateralConfiguration()
                        case 0x5a7ff7c5 { result := _REWARDS_MANAGER_MODULE } // RewardsManagerModule.distributeRewards()
                        case 0x5d8c8844 { result := _POOL_MODULE } // PoolModule.setPoolConfiguration()
                        case 0x5e52ad6e { result := _FEATURE_FLAG_MODULE } // FeatureFlagModule.setFeatureFlagDenyAll()
                        case 0x60248c55 { result := _VAULT_MODULE } // VaultModule.getVaultCollateralRatio()
                        leave
                    }
                    if lt(sig,0x75bf2444) {
                        switch sig
                        case 0x60988e09 { result := _ASSOCIATED_SYSTEMS_MODULE } // AssociatedSystemsModule.getAssociatedSystem()
                        case 0x6141f7a2 { result := _POOL_MODULE } // PoolModule.nominatePoolOwner()
                        case 0x644cb0f3 { result := _COLLATERAL_CONFIGURATION_MODULE } // CollateralConfigurationModule.configureCollateral()
                        case 0x645657d8 { result := _REWARDS_MANAGER_MODULE } // RewardsManagerModule.updateRewards()
                        case 0x6dd5b69d { result := _UTILS_MODULE } // UtilsModule.getConfig()
                        case 0x6fd5bdce { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.setMinLiquidityRatio()
                        case 0x715cb7d2 { result := _FEATURE_FLAG_MODULE } // FeatureFlagModule.setDeniers()
                        case 0x718fe928 { result := _INITIAL_MODULE_BUNDLE } // InitialModuleBundle.renounceNomination()
                        case 0x741a5d3f { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.getMarketCapacityContributionFromPool()
                        leave
                    }
                    switch sig
                    case 0x75bf2444 { result := _COLLATERAL_CONFIGURATION_MODULE } // CollateralConfigurationModule.getCollateralConfigurations()
                    case 0x79ba5097 { result := _INITIAL_MODULE_BUNDLE } // InitialModuleBundle.acceptOwnership()
                    case 0x7a75c869 { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.getMarketPoolMaxDebtPerShare()
                    case 0x7b0532a4 { result := _VAULT_MODULE } // VaultModule.delegateCollateral()
                    case 0x7cc14a92 { result := _POOL_MODULE } // PoolModule.renouncePoolOwnership()
                    case 0x7d632bd2 { result := _FEATURE_FLAG_MODULE } // FeatureFlagModule.setFeatureFlagAllowAll()
                    case 0x7d8a4140 { result := _LIQUIDATION_MODULE } // LiquidationModule.liquidateVault()
                    case 0x7dec8b55 { result := _ACCOUNT_MODULE } // AccountModule.notifyAccountTransfer()
                    leave
                }
                if lt(sig,0xc4b3410e) {
                    if lt(sig,0xa4e6306b) {
                        if lt(sig,0x95909ba3) {
                            switch sig
                            case 0x830e23b5 { result := _UTILS_MODULE } // UtilsModule.setSupportedCrossChainNetworks()
                            case 0x83802968 { result := _COLLATERAL_MODULE } // CollateralModule.deposit()
                            case 0x84f29b6d { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.getMinLiquidityRatio()
                            case 0x85572ffb { result := _CCIP_RECEIVER_MODULE } // CcipReceiverModule.ccipReceive()
                            case 0x85d99ebc { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.getMarketNetIssuance()
                            case 0x86e3b1cf { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.getMarketReportedDebt()
                            case 0x8d34166b { result := _ACCOUNT_MODULE } // AccountModule.hasPermission()
                            case 0x8da5cb5b { result := _INITIAL_MODULE_BUNDLE } // InitialModuleBundle.owner()
                            case 0x927482ff { result := _COLLATERAL_MODULE } // CollateralModule.getAccountAvailableCollateral()
                            leave
                        }
                        switch sig
                        case 0x95909ba3 { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.getMarketDebtPerShare()
                        case 0x95997c51 { result := _COLLATERAL_MODULE } // CollateralModule.withdraw()
                        case 0x9851af01 { result := _POOL_MODULE } // PoolModule.getNominatedPoolOwner()
                        case 0x9b20dc89 { result := _POOL_MODULE } // PoolModule.getPoolTotalDebt()
                        case 0x9dca362f { result := _ACCOUNT_MODULE } // AccountModule.createAccount()
                        case 0xa0778144 { result := _FEATURE_FLAG_MODULE } // FeatureFlagModule.addToFeatureFlagAllowlist()
                        case 0xa0c12269 { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.distributeDebtToPools()
                        case 0xa148bf10 { result := _ACCOUNT_MODULE } // AccountModule.getAccountTokenAddress()
                        case 0xa3aa8b51 { result := _MARKET_COLLATERAL_MODULE } // MarketCollateralModule.withdrawMarketCollateral()
                        leave
                    }
                    if lt(sig,0xb790a1ae) {
                        switch sig
                        case 0xa4e6306b { result := _MARKET_COLLATERAL_MODULE } // MarketCollateralModule.depositMarketCollateral()
                        case 0xa5d49393 { result := _UTILS_MODULE } // UtilsModule.configureOracleManager()
                        case 0xa7627288 { result := _ACCOUNT_MODULE } // AccountModule.revokePermission()
                        case 0xa796fecd { result := _ACCOUNT_MODULE } // AccountModule.getAccountPermissions()
                        case 0xa79b9ec9 { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.registerMarket()
                        case 0xaa8c6369 { result := _COLLATERAL_MODULE } // CollateralModule.getLocks()
                        case 0xaaf10f42 { result := _INITIAL_MODULE_BUNDLE } // InitialModuleBundle.getImplementation()
                        case 0xb01ceccd { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.getOracleManager()
                        case 0xb7746b59 { result := _FEATURE_FLAG_MODULE } // FeatureFlagModule.removeFromFeatureFlagAllowlist()
                        leave
                    }
                    switch sig
                    case 0xb790a1ae { result := _POOL_CONFIGURATION_MODULE } // PoolConfigurationModule.addApprovedPool()
                    case 0xb7e3e68c { result := _VAULT_MODULE } // VaultModule.migrateDelegation()
                    case 0xbaa2a264 { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.getMarketTotalDebt()
                    case 0xbbdd7c5a { result := _POOL_MODULE } // PoolModule.getPoolOwner()
                    case 0xbcae3ea0 { result := _FEATURE_FLAG_MODULE } // FeatureFlagModule.getFeatureFlagDenyAll()
                    case 0xbe0b8e6f { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.getMarketPools()
                    case 0xbf60c31d { result := _ACCOUNT_MODULE } // AccountModule.getAccountOwner()
                    case 0xc2b0cf41 { result := _MARKET_COLLATERAL_MODULE } // MarketCollateralModule.getMarketCollateralAmount()
                    leave
                }
                if lt(sig,0xdc0a5384) {
                    if lt(sig,0xce1b815f) {
                        switch sig
                        case 0xc4b3410e { result := _REWARDS_MANAGER_MODULE } // RewardsManagerModule.getAvailableRewards()
                        case 0xc4d2aad3 { result := _POOL_MODULE } // PoolModule.getPoolCollateralIssuanceRatio()
                        case 0xc6f79537 { result := _ASSOCIATED_SYSTEMS_MODULE } // AssociatedSystemsModule.initOrUpgradeToken()
                        case 0xc707a39f { result := _POOL_MODULE } // PoolModule.acceptPoolOwnership()
                        case 0xc77e51f6 { result := _POOL_MODULE } // PoolModule.getPoolCollateralConfiguration()
                        case 0xc7f62cda { result := _INITIAL_MODULE_BUNDLE } // InitialModuleBundle.simulateUpgradeTo()
                        case 0xca5bed77 { result := _POOL_MODULE } // PoolModule.renouncePoolNomination()
                        case 0xcaab529b { result := _POOL_MODULE } // PoolModule.createPool()
                        case 0xcadb09a5 { result := _ACCOUNT_MODULE } // AccountModule.createAccount()
                        leave
                    }
                    switch sig
                    case 0xce1b815f { result := _UTILS_MODULE } // UtilsModule.getTrustedForwarder()
                    case 0xcf635949 { result := _FEATURE_FLAG_MODULE } // FeatureFlagModule.isFeatureAllowed()
                    case 0xd1fd27b3 { result := _UTILS_MODULE } // UtilsModule.setConfig()
                    case 0xd24437f1 { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.getMarketAddress()
                    case 0xd245d983 { result := _ASSOCIATED_SYSTEMS_MODULE } // AssociatedSystemsModule.registerUnmanagedSystem()
                    case 0xd3264e43 { result := _ISSUE_USDMODULE } // IssueUSDModule.burnUsd()
                    case 0xd4f88381 { result := _MARKET_COLLATERAL_MODULE } // MarketCollateralModule.getMarketCollateralValue()
                    case 0xdbdea94c { result := _MARKET_COLLATERAL_MODULE } // MarketCollateralModule.configureMaximumMarketCollateral()
                    leave
                }
                if lt(sig,0xef45148e) {
                    switch sig
                    case 0xdc0a5384 { result := _VAULT_MODULE } // VaultModule.getPositionCollateralRatio()
                    case 0xdc0b3f52 { result := _COLLATERAL_CONFIGURATION_MODULE } // CollateralConfigurationModule.getCollateralConfiguration()
                    case 0xdf16a074 { result := _ISSUE_USDMODULE } // IssueUSDModule.mintUsd()
                    case 0xdfb83437 { result := _MARKET_MANAGER_MODULE } // MarketManagerModule.getMarketFees()
                    case 0xe12c8160 { result := _FEATURE_FLAG_MODULE } // FeatureFlagModule.getFeatureFlagAllowlist()
                    case 0xe1b440d0 { result := _POOL_CONFIGURATION_MODULE } // PoolConfigurationModule.removeApprovedPool()
                    case 0xe7098c0c { result := _POOL_CONFIGURATION_MODULE } // PoolConfigurationModule.setPreferredPool()
                    case 0xeaeacda3 { result := _REWARDS_MANAGER_MODULE } // RewardsManagerModule.getAvailablePoolRewards()
                    case 0xed429cf7 { result := _FEATURE_FLAG_MODULE } // FeatureFlagModule.getDeniers()
                    leave
                }
                switch sig
                case 0xef45148e { result := _COLLATERAL_MODULE } // CollateralModule.getAccountCollateral()
                case 0xefecf137 { result := _POOL_MODULE } // PoolModule.getPoolConfiguration()
                case 0xf544d66e { result := _VAULT_MODULE } // VaultModule.getPosition()
                case 0xf86e6f91 { result := _POOL_MODULE } // PoolModule.getPoolName()
                case 0xf896503a { result := _UTILS_MODULE } // UtilsModule.getConfigAddress()
                case 0xf92bb8c9 { result := _UTILS_MODULE } // UtilsModule.getConfigUint()
                case 0xfd85c1f8 { result := _POOL_MODULE } // PoolModule.getMinLiquidityRatio()
                case 0xfd93aa76 { result := _VAULT_MODULE } // VaultModule.getLastDelegationTime()
                leave
            }

            implementation := findImplementation(sig32)
        }

        if (implementation == address(0)) {
            // It's possible this contract is being called through yet another proxy. Call the router in order to make sure we have right data.
            if (address(this) != _ROUTER_ADDRESS) {
                (bool success, bytes memory result) = _ROUTER_ADDRESS.call(cd);
                if (success) {
                    return result;
                } else {
                    revert UnknownSelector(sig4);
                }
            } else {
                // Check for diamond compat call
                if (sig4 == 0x7a0ed627) {
                    return abi.encode(_facets());
                }
                if (sig4 == 0xadfca15e) {
                    (address facet) = abi.decode(cd[4:], (address));
                    return abi.encode(_facetFunctionSelectors(facet));
                }
                if (sig4 == 0x52ef6b2c) {
                    return abi.encode(_facetAddresses());
                }
                if (sig4 == 0xcdffacc6) {
                    (bytes4 sig) = abi.decode(cd[4:], (bytes4));
                    return abi.encode(_facetAddress(sig));
                }
                if (sig4 == 0x8cce96cb) {
                    return abi.encode(_emitDiamondCutEvent());
                }
            }
            revert UnknownSelector(sig4);
        }

        // Delegatecall to the implementation contract
        assembly {
            calldatacopy(0, 0, calldatasize())

            let result := delegatecall(gas(), implementation, 0, calldatasize(), 0, 0)
            returndatacopy(0, 0, returndatasize())

            switch result
            case 0 {
                revert(0, returndatasize())
            }
            default {
                return(0, returndatasize())
            }
        }
    }

    struct Facet {
        address facetAddress;
        bytes4[] functionSelectors;
    }

    enum FacetCutAction {Add, Replace, Remove}
    // Add=0, Replace=1, Remove=2

    struct FacetCut {
        address facetAddress;
        FacetCutAction action;
        bytes4[] functionSelectors;
    }

    /// @notice Gets all facet addresses and their four byte function selectors.
    /// @return facets_ Facet
    function _facets() internal pure returns (Facet[] storage facets_) {
        bytes32 s = keccak256("Router.CoreRouter");
        assembly {
            facets_.slot := s
        }
    }

    /// @notice Gets all the function selectors supported by a specific facet.
    /// @param _facet The facet address.
    /// @return facetFunctionSelectors_
    function _facetFunctionSelectors(address _facet) internal view returns (bytes4[] memory facetFunctionSelectors_) {
        Facet[] storage facets = _facets();
        for (uint256 i = 0;i < facets.length;i++) {
            if (facets[i].facetAddress == _facet) {
                return facets[i].functionSelectors;
            }
        }
    }

    /// @notice Get all the facet addresses used by a diamond.
    /// @return facetAddresses_
    function _facetAddresses() internal pure returns (address[] memory facetAddresses_) {
        facetAddresses_ = new address[](18);
        facetAddresses_[0] = _INITIAL_MODULE_BUNDLE;
        facetAddresses_[1] = _FEATURE_FLAG_MODULE;
        facetAddresses_[2] = _ACCOUNT_MODULE;
        facetAddresses_[3] = _ASSOCIATE_DEBT_MODULE;
        facetAddresses_[4] = _ASSOCIATED_SYSTEMS_MODULE;
        facetAddresses_[5] = _CCIP_RECEIVER_MODULE;
        facetAddresses_[6] = _COLLATERAL_MODULE;
        facetAddresses_[7] = _COLLATERAL_CONFIGURATION_MODULE;
        facetAddresses_[8] = _CROSS_CHAIN_USDMODULE;
        facetAddresses_[9] = _ISSUE_USDMODULE;
        facetAddresses_[10] = _LIQUIDATION_MODULE;
        facetAddresses_[11] = _MARKET_COLLATERAL_MODULE;
        facetAddresses_[12] = _MARKET_MANAGER_MODULE;
        facetAddresses_[13] = _POOL_CONFIGURATION_MODULE;
        facetAddresses_[14] = _POOL_MODULE;
        facetAddresses_[15] = _REWARDS_MANAGER_MODULE;
        facetAddresses_[16] = _UTILS_MODULE;
        facetAddresses_[17] = _VAULT_MODULE;
    }

    /// @notice Gets the facet that supports the given selector.
    /// @dev If facet is not found return address(0).
    /// @param _functionSelector The function selector.
    /// @return facetAddress_ The facet address.
    function _facetAddress(bytes4 _functionSelector) internal view returns (address facetAddress_) {
        Facet[] storage facets = _facets();
        for (uint256 i = 0;i < facets.length;i++) {
            for (uint256 j = 0;j < facets[i].functionSelectors.length;j++) {
                if (facets[i].functionSelectors[j] == _functionSelector) {
                    return facets[i].facetAddress;
                }
            }
        }
    }

    event DiamondCut(FacetCut[] _diamondCut, address _init, bytes _calldata);

    /// @notice Emits the cut events that would be emitted if this was actually a diamond
    function _emitDiamondCutEvent() internal returns (bool) {
        FacetCut[] memory cuts = new FacetCut[](18);
        cuts[0] = FacetCut(_INITIAL_MODULE_BUNDLE, FacetCutAction.Add, _facetFunctionSelectors(_INITIAL_MODULE_BUNDLE));
        cuts[1] = FacetCut(_FEATURE_FLAG_MODULE, FacetCutAction.Add, _facetFunctionSelectors(_FEATURE_FLAG_MODULE));
        cuts[2] = FacetCut(_ACCOUNT_MODULE, FacetCutAction.Add, _facetFunctionSelectors(_ACCOUNT_MODULE));
        cuts[3] = FacetCut(_ASSOCIATE_DEBT_MODULE, FacetCutAction.Add, _facetFunctionSelectors(_ASSOCIATE_DEBT_MODULE));
        cuts[4] = FacetCut(_ASSOCIATED_SYSTEMS_MODULE, FacetCutAction.Add, _facetFunctionSelectors(_ASSOCIATED_SYSTEMS_MODULE));
        cuts[5] = FacetCut(_CCIP_RECEIVER_MODULE, FacetCutAction.Add, _facetFunctionSelectors(_CCIP_RECEIVER_MODULE));
        cuts[6] = FacetCut(_COLLATERAL_MODULE, FacetCutAction.Add, _facetFunctionSelectors(_COLLATERAL_MODULE));
        cuts[7] = FacetCut(_COLLATERAL_CONFIGURATION_MODULE, FacetCutAction.Add, _facetFunctionSelectors(_COLLATERAL_CONFIGURATION_MODULE));
        cuts[8] = FacetCut(_CROSS_CHAIN_USDMODULE, FacetCutAction.Add, _facetFunctionSelectors(_CROSS_CHAIN_USDMODULE));
        cuts[9] = FacetCut(_ISSUE_USDMODULE, FacetCutAction.Add, _facetFunctionSelectors(_ISSUE_USDMODULE));
        cuts[10] = FacetCut(_LIQUIDATION_MODULE, FacetCutAction.Add, _facetFunctionSelectors(_LIQUIDATION_MODULE));
        cuts[11] = FacetCut(_MARKET_COLLATERAL_MODULE, FacetCutAction.Add, _facetFunctionSelectors(_MARKET_COLLATERAL_MODULE));
        cuts[12] = FacetCut(_MARKET_MANAGER_MODULE, FacetCutAction.Add, _facetFunctionSelectors(_MARKET_MANAGER_MODULE));
        cuts[13] = FacetCut(_POOL_CONFIGURATION_MODULE, FacetCutAction.Add, _facetFunctionSelectors(_POOL_CONFIGURATION_MODULE));
        cuts[14] = FacetCut(_POOL_MODULE, FacetCutAction.Add, _facetFunctionSelectors(_POOL_MODULE));
        cuts[15] = FacetCut(_REWARDS_MANAGER_MODULE, FacetCutAction.Add, _facetFunctionSelectors(_REWARDS_MANAGER_MODULE));
        cuts[16] = FacetCut(_UTILS_MODULE, FacetCutAction.Add, _facetFunctionSelectors(_UTILS_MODULE));
        cuts[17] = FacetCut(_VAULT_MODULE, FacetCutAction.Add, _facetFunctionSelectors(_VAULT_MODULE));
        emit DiamondCut(cuts, address(0), new bytes(0));
        return true;
    }
}
