// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.27;

import {Lib_OVMCodec} from "@eth-optimism/contracts/libraries/codec/Lib_OVMCodec.sol";
import {Lib_SecureMerkleTrie} from "@eth-optimism/contracts/libraries/trie/Lib_SecureMerkleTrie.sol";
import {Lib_RLPReader} from "@eth-optimism/contracts/libraries/rlp/Lib_RLPReader.sol";
import {Lib_BytesUtils} from "@eth-optimism/contracts/libraries/utils/Lib_BytesUtils.sol";

import {IProofVerifier} from "./interfaces/IProofVerifier.sol";

/// MPT proof verifier allows to validate witness proof about a storage slot value on the other chain.
/// @custom:security-contact security@fantom.foundation
contract MPTProofVerifier is IProofVerifier {

    /// Verify proof generated by eth_getProof
    function verifyProof(address contractAddress, bytes32 slotIndex, bytes32 expectedValue, bytes32 stateRoot, bytes calldata proof) external pure {
        Lib_RLPReader.RLPItem[] memory proofItems = Lib_RLPReader.readList(proof);
        require(proofItems.length == 2, "Expected 2 proof parts");
        bytes memory accountProof = Lib_RLPReader.readBytes(proofItems[0]);
        bytes memory storageProof = Lib_RLPReader.readBytes(proofItems[1]);

        // MPT witness proof verification
        // https://github.com/ensdomains/arb-resolver/blob/master/packages/contracts/contracts/l1/ArbitrumResolverStub.sol#L166
        // https://github.com/ensdomains/op-resolver/blob/master/packages/contracts/contracts/l1/OptimismResolverStub.sol#L135
        (
            bool exists,
            bytes memory encodedAccount
        ) = Lib_SecureMerkleTrie.get(
                abi.encodePacked(contractAddress),
                accountProof,
                stateRoot
            );
        require(exists, "Proved account does not exist");
        Lib_OVMCodec.EVMAccount memory account = Lib_OVMCodec.decodeEVMAccount(
            encodedAccount
        );

        (bool storageExists, bytes memory retrievedValue) = Lib_SecureMerkleTrie
            .get(
                abi.encodePacked(slotIndex),
                storageProof,
                account.storageRoot
            );

        if (!storageExists) {
            require(expectedValue == 0, "Unexpected proved value");
        } else {
            bytes32 actualValue = toBytes32PadLeft(Lib_RLPReader.readBytes(retrievedValue));
            require(actualValue == expectedValue, "Unexpected proved value");
        }
    }

    /// Convert RLP bytes value to bytes32
    // Ported from Lib_BytesUtils.sol / OptimismResolverStub.sol
    function toBytes32PadLeft(bytes memory _bytes) private pure returns (bytes32) {
        bytes32 ret;
        uint256 len = _bytes.length <= 32 ? _bytes.length : 32;
        assembly {
            ret := shr(mul(sub(32, len), 8), mload(add(_bytes, 32)))
        }
        return ret;
    }
}
