// SPDX-License-Identifier: MIT
pragma solidity ^0.8.29;

// SprBTC Vault Tables
bytes32 constant SPRBTC_COLLATERAL_TABLE = "SPRBTC_COLLATERAL";
bytes32 constant SPRBTC_FEE_TABLE = "SPRBTC_FEE";
bytes32 constant SPRBTC_CONFIG_TABLE = "SPRBTC_CONFIG";
bytes32 constant SPRBTC_EXCHANGE_RATE_TABLE = "SPRBTC_EXCHANGE_RATE";
bytes32 constant SPRBTC_QUEUE_TABLE = "SPRBTC_QUEUE";
bytes32 constant SPRBTC_ADDRESSES_TABLE = "SPRBTC_ADDRESSES";
