// SPDX-License-Identifier: UNLICENSED

pragma solidity ^0.8.10;

// Using @openzeppelin/contracts-upgradeable@4.3.2
import "@openzeppelin/contracts-upgradeable/token/ERC721/ERC721Upgradeable.sol";
import "@openzeppelin/contracts-upgradeable/token/ERC721/extensions/ERC721EnumerableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/token/ERC721/extensions/ERC721BurnableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/token/ERC721/extensions/ERC721PausableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/access/AccessControlEnumerableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/utils/ContextUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/utils/CountersUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/token/ERC20/utils/SafeERC20Upgradeable.sol";

interface IVault {
    function deposit(uint256 _amount) external;

    function withdraw(uint256 _shares) external;
}

/**
 * @dev {ERC721} token, including:
 *
 *  - ability for holders to burn (destroy) their tokens
 *  - a minter role that allows for token minting (creation)
 *  - a pauser role that allows to stop all token transfers
 *  - token ID and URI autogeneration
 *
 * This contract uses {AccessControl} to lock permissioned functions using the
 * different roles - head to its documentation for details.
 *
 * The account that deploys the contract will be granted the minter and pauser
 * roles, as well as the default admin role, which will let it grant both minter
 * and pauser roles to other accounts.
 */
contract ACryptoSINFT is
    Initializable,
    ContextUpgradeable,
    AccessControlEnumerableUpgradeable,
    ERC721EnumerableUpgradeable,
    ERC721BurnableUpgradeable,
    ERC721PausableUpgradeable,
    UUPSUpgradeable
{
    using CountersUpgradeable for CountersUpgradeable.Counter;
    using SafeERC20Upgradeable for IERC20Upgradeable;

    address constant ADMIN =
        address(0xB9a81e121d8C9D619682bB9dDB6823439178F2f8);

    bytes32 public constant MINTER_ROLE = keccak256("MINTER_ROLE");
    bytes32 public constant PAUSER_ROLE = keccak256("PAUSER_ROLE");

    address constant STAKE_TOKEN =
        address(0x5b17b4d5e4009B5C43e3e3d63A5229F794cBA389); // ACSI
    address constant STAKE_VAULT =
        address(0x2b66399AD01be47C5aa11C48fDd6DF689DAE929A); // acsACSI
    uint256 constant STAKE_MIN = 38e18;
    uint256 constant STAKE_TOKEN_FEE = 0.12e18; // 0.12e18 = 18%
    address constant STAKE_TOKEN_FEE_TO =
        address(0x5BD97307A40DfBFDBAEf4B3d997ADB816F2dadCC); // ACryptoS Treasury
    uint256 constant AVERAGE_DURATION = 1 weeks; // used to calculate ownerAverageBalanceOfStakedVault

    CountersUpgradeable.Counter private _tokenIdTracker;

    mapping(uint256 => uint256) public balanceOfStakedVault; // staked vault tokens in each NFT
    mapping(address => uint256) public ownerBalanceOfStakedVault; // staked vault tokens of each owner
    mapping(address => uint256) public ownerAverageBalanceOfStakedVaultLast;
    mapping(address => uint256) public ownerAverageBalanceOfStakedVaultLastAt;

    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() initializer {}

    function initialize(string memory name, string memory symbol)
        public
        virtual
        initializer
    {
        __ACryptoSINFT_init(name, symbol);
    }

    /**
     * @dev Grants `DEFAULT_ADMIN_ROLE`, `MINTER_ROLE` and `PAUSER_ROLE` to the
     * account that deploys the contract.
     *
     * Token URIs will be autogenerated based on `baseURI` and their token IDs.
     * See {ERC721-tokenURI}.
     */
    function __ACryptoSINFT_init(string memory name, string memory symbol)
        internal
        initializer
    {
        __Context_init_unchained();
        __ERC165_init_unchained();
        __AccessControl_init_unchained();
        __AccessControlEnumerable_init_unchained();
        __ERC721_init_unchained(name, symbol);
        __ERC721Enumerable_init_unchained();
        __ERC721Burnable_init_unchained();
        __Pausable_init_unchained();
        __ERC721Pausable_init_unchained();

        __ERC1967Upgrade_init_unchained();
        __UUPSUpgradeable_init_unchained();

        __ACryptoSINFT_init_unchained(name, symbol);
    }

    function __ACryptoSINFT_init_unchained(
        string memory name,
        string memory symbol
    ) internal initializer {
        _setupRole(DEFAULT_ADMIN_ROLE, ADMIN);

        _setupRole(MINTER_ROLE, ADMIN);
        _setupRole(PAUSER_ROLE, ADMIN);

        IERC20Upgradeable(STAKE_TOKEN).approve(STAKE_VAULT, type(uint256).max);
    }

    function _baseURI() internal view virtual override returns (string memory) {
        return "https://nft-data.acryptos.com/acsi/";
    }

    /**
     * @dev Creates a new token for `to`. Its token ID will be automatically
     * assigned (and available on the emitted {IERC721-Transfer} event), and the token
     * URI autogenerated based on the base URI passed at construction.
     *
     * See {ERC721-_mint}.
     *
     * Requirements:
     *
     * - the caller must have the `MINTER_ROLE`.
     */
    function mint(address to) public virtual {
        mintWithStake(to, 0);
    }

    function mintWithStake(address to, uint256 amount) public virtual {
        if (
            _tokenIdTracker.current() < 2 ||
            _tokenIdTracker.current() >= 1890 ||
            amount < STAKE_MIN
        ) {
            require(hasRole(MINTER_ROLE, _msgSender()), "!minter");
        }

        _stake(_msgSender(), amount, _tokenIdTracker.current());

        _mint(to, _tokenIdTracker.current());
        _tokenIdTracker.increment();
    }

    /**
     * @dev Pauses all token transfers.
     *
     * See {ERC721Pausable} and {Pausable-_pause}.
     *
     * Requirements:
     *
     * - the caller must have the `PAUSER_ROLE`.
     */
    function pause() public virtual onlyRole(PAUSER_ROLE) {
        _pause();
    }

    /**
     * @dev Unpauses all token transfers.
     *
     * See {ERC721Pausable} and {Pausable-_unpause}.
     *
     * Requirements:
     *
     * - the caller must have the `PAUSER_ROLE`.
     */
    function unpause() public virtual onlyRole(PAUSER_ROLE) {
        _unpause();
    }

    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 tokenId
    )
        internal
        virtual
        override(
            ERC721Upgradeable,
            ERC721EnumerableUpgradeable,
            ERC721PausableUpgradeable
        )
    {
        super._beforeTokenTransfer(from, to, tokenId);

        if (from == address(0)) {
            // _stake() is called from mintToStake()
        } else if (from != to) {
            _updateOwnerAverageBalanceOfStakedVault(from);
            ownerBalanceOfStakedVault[from] -= balanceOfStakedVault[tokenId];
        }
        if (to == address(0)) {
            _returnStakeToOwner(from, tokenId);
        } else if (to != from) {
            _updateOwnerAverageBalanceOfStakedVault(to);
            ownerBalanceOfStakedVault[to] += balanceOfStakedVault[tokenId];
        }
    }

    function _updateOwnerAverageBalanceOfStakedVault(address owner) private {
        if (ownerAverageBalanceOfStakedVaultLastAt[owner] >= block.timestamp)
            return;

        ownerAverageBalanceOfStakedVaultLast[
            owner
        ] = ownerAverageBalanceOfStakedVault(owner); // must get this before setting lastAt
        ownerAverageBalanceOfStakedVaultLastAt[owner] = block.timestamp;
    }

    function ownerAverageBalanceOfStakedVault(address owner)
        public
        view
        returns (uint256 balance)
    {
        uint256 lastWeight = ownerAverageBalanceOfStakedVaultLastAt[owner] >
            block.timestamp - AVERAGE_DURATION
            ? ownerAverageBalanceOfStakedVaultLastAt[owner] -
                (block.timestamp - AVERAGE_DURATION)
            : 0;
        balance =
            (ownerAverageBalanceOfStakedVaultLast[owner] *
                lastWeight +
                ownerBalanceOfStakedVault[owner] *
                (AVERAGE_DURATION - lastWeight)) /
            AVERAGE_DURATION;
    }

    function _stake(
        address from,
        uint256 amount,
        uint256 tokenId
    ) private {
        uint256 fee = (amount * STAKE_TOKEN_FEE) / 1e18;
        amount = amount - fee;

        IERC20Upgradeable(STAKE_TOKEN).safeTransferFrom(
            from,
            STAKE_TOKEN_FEE_TO,
            fee
        );

        IERC20Upgradeable(STAKE_TOKEN).safeTransferFrom(
            from,
            address(this),
            amount
        );

        uint256 amountVault = IERC20Upgradeable(STAKE_VAULT).balanceOf(
            address(this)
        );

        IVault(STAKE_VAULT).deposit(amount);

        amountVault =
            IERC20Upgradeable(STAKE_VAULT).balanceOf(address(this)) -
            amountVault;

        balanceOfStakedVault[tokenId] = amountVault;
    }

    function _returnStakeToOwner(address to, uint256 tokenId) private {
        uint256 amountStakedVault = balanceOfStakedVault[tokenId];
        balanceOfStakedVault[tokenId] = 0;

        uint256 amountStake = IERC20Upgradeable(STAKE_TOKEN).balanceOf(
            address(this)
        );

        IVault(STAKE_VAULT).withdraw(amountStakedVault);

        amountStake =
            IERC20Upgradeable(STAKE_TOKEN).balanceOf(address(this)) -
            amountStake;

        IERC20Upgradeable(STAKE_TOKEN).safeTransfer(to, amountStake);
    }

    /**
     * @dev See {IERC165-supportsInterface}.
     */
    function supportsInterface(bytes4 interfaceId)
        public
        view
        virtual
        override(
            AccessControlEnumerableUpgradeable,
            ERC721Upgradeable,
            ERC721EnumerableUpgradeable
        )
        returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }

    function _authorizeUpgrade(address newImplementation)
        internal
        virtual
        override
        onlyRole(DEFAULT_ADMIN_ROLE)
    {}
}
