// SPDX-License-Identifier: AGPL-3.0
pragma solidity 0.8.13;

import './IAdapter.sol';

/**
 * @notice ICustodian
 * @author Atlendis Labs
 * @notice Interface of the Custodian contract
 *         A custodian contract is associated to a product contract.
 *         It receives funds by the associated product contract.
 *         A yield strategy is chosen in order to generate rewards based on the deposited funds.
 */
interface IPoolCustodian is IAdapter {
    /**
     * @notice Deposit tokens to the custodian using current adapter and yield provider
     **/
    event Deposit(uint256 amount, address adapter, address yieldProvider);

    /**
     * @notice Withdraw tokens to the custodian using current adapter and yield provider
     **/
    event Withdraw(uint256 amount, address adapter, address yieldProvider);

    /**
     * @notice Move funds from old yield provider to new yield provider
     **/
    event SwitchYieldProvider(address adapter, address yieldProvider);

    /**
     * @notice Update pending rewards
     **/
    event CollectRewards(uint256 amount);

    /**
     * @notice Withdraw pending rewards
     **/
    event WithdrawRewards(uint256 amount);

    /**
     * @notice Changes the yield provider used by the custodian
     * @param newAdapter New adapter used to manage yield provider interaction
     * @param newYieldProvider New yield provider address
     **/
    function switchYieldProvider(address newAdapter, address newYieldProvider) external;

    /**
     * @notice Withdraw an amount of rewards
     * @param amount The amount of rewards to be withdrawn
     * @param to Address that will receive the rewards
     **/
    function withdrawRewards(uint256 amount, address to) external;

    /**
     * @notice Retrieve the rewards generated by the custodian
     * @return rewards Amount of rewards
     */
    function getRewards() external view returns (uint256 rewards);

    /**
     * @notice Retrieve the decimals of the underlying asset
     & @return decimals Decimals of the underlying asset
     */
    function getAssetDecimals() external view returns (uint256 decimals);
}
