// SPDX-License-Identifier: UNLICENSED
/*
Generated by ChainGPT AI NFT app
www.ChainGPT.org

Disclaimer: This smart contract collection is independently created and not owned 
or associated with ChainGPT. It is important to note that the content of this 
collection has been solely generated by the AI tools provided through the ChainGPT 
platform. ChainGPT does not endorse or assume any responsibility for the accuracy,
reliability, or legality of the contents within this collection. Users are advised 
to exercise caution and conduct their own due diligence before engaging with this 
smart contract collection. By using this smart contract, you acknowledge and agree 
that ChainGPT is not liable for any damages or losses incurred as a result of your 
interactions with this collection.
*/

pragma solidity ^0.8.0;

import "./dependencies/Ownable.sol";
import "./dependencies/EnumerableSet.sol";

/**
 * @title ChainGPT NFT Blacklist
 * @author Tammy
 * @notice This contract manages the blacklisting of NFT collections.
 * @custom:version 1.0.0
 * @custom:default-precision 0
 * @custom:simple-description CGPT NFT Blacklist contract that has been created by ChainGPT AI. 
 * @dev This contract allows the addition and removal of admin wallets and blacklisted collections. 
 *
 * Admin wallets have the authority to add or remove collections from the blacklist. 
 * Blacklisted collections are restricted from certain functionalities. 
 *
 */

contract CGPTNFTBlacklist is Ownable {
    using EnumerableSet for EnumerableSet.AddressSet;

    // Declare EnumerableSets to store addresses
    EnumerableSet.AddressSet private adminSet;
    EnumerableSet.AddressSet private blacklistSet;

    // Events
    event AdminAdded(address indexed admin);
    event AdminRemoved(address indexed admin);
    event BlacklistAdded(address indexed collection);
    event BlacklistRemoved(address indexed collection);

    /** 
     * @dev Constructor function. 
     * Sets the deployer of the contract as an admin wallet. 
     */ 
    constructor() Ownable() {
        _addAdmin(msg.sender);
    }

    /** 
     * @dev Adds an admin wallet. 
     * Only the contract owner can call this function. 
     * @param wallet The address of the wallet to be added as an admin. 
     */ 
    function addAdmin(address wallet) public onlyOwner {
        _addAdmin(wallet);
    }

    /** 
     * @dev Removes an admin wallet. 
     * Only the contract owner can call this function. 
     * @param wallet The address of the wallet to be removed as an admin. 
     */ 
    function removeAdmin(address wallet) public onlyOwner {
        _removeAdmin(wallet);
    }

    /** 
     * @dev Checks if an address is an admin wallet. 
     * @param wallet The address to be checked. 
     */ 
    function isAdmin(address wallet) public view returns (bool) {
        return adminSet.contains(wallet);
    }

    /**
     * @dev Gets the admin address at a specific index.
     * @param _index The index of the admin address.
     * @return The admin address at the specified index.
     */
    function getAdminAddressAtIndex(uint256 _index) public view returns (address) {
        return adminSet.at(_index);
    }

    /** 
     * @dev Gets all admin wallets. 
     */
    function getAllAdmins() public view returns (address[] memory) {
        return adminSet.values();
    }

    /** 
     * @dev Adds a blacklisted collection. 
     * Only admin wallets can call this function. 
     * @param collection The address representing the blacklisted collection. 
     */ 
    function addBlacklist(address collection) public {
        require(adminSet.contains(msg.sender), "Caller is not the admin");
        _addBlacklist(collection);
    }

    /** 
     * @dev Removes a blacklisted collection. 
     * Only admin wallets can call this function. 
     * @param collection The address representing the blacklisted collection. 
     */
    function removeBlacklist(address collection) public {
        require(adminSet.contains(msg.sender), "Caller is not the admin");
        _removeBlacklist(collection);
    }

    /** 
     * @dev Checks if a collection is blacklisted. 
     * @param collection The address representing the collection. 
     */ 
    function isBlacklisted(address collection) public view returns (bool) {
        return blacklistSet.contains(collection);
    }

    /**
     * @dev Gets the blacklisted collection address at a specific index.
     * @param _index The index of the blacklisted collection address.
     * @return The blacklisted collection address at the specified index.
     */
    function getBlacklistAddressAtIndex(uint256 _index) public view returns (address) {
        return blacklistSet.at(_index);
    }

    /** 
     * @dev Gets all blacklisted collections. 
     */ 
    function getAllBlacklistedCollections() public view returns (address[] memory) {
        return blacklistSet.values();
    }

    function _addAdmin(address wallet) internal {
        require(wallet != address(0), "Invalid wallet address");
        require(!isAdmin(wallet), "Wallet is already an admin");
        adminSet.add(wallet);
        emit AdminAdded(wallet);
    }

    function _removeAdmin(address wallet) internal {
        require(isAdmin(wallet), "Wallet is not an admin");
        require(adminSet.length() > 1, "At least one admin is required");
        adminSet.remove(wallet);
        emit AdminRemoved(wallet);
    }

    function _addBlacklist(address collection) internal {
        require(collection != address(0), "Invalid collection address");
        require(!isBlacklisted(collection), "Collection is already blacklisted");
        blacklistSet.add(collection);
        emit BlacklistAdded(collection);
    }

    function _removeBlacklist(address collection) internal {
        require(isBlacklisted(collection), "Collection is not blacklisted");
        blacklistSet.remove(collection);
        emit BlacklistRemoved(collection);
    }
}