/*
* Generated by @Thrasher66099
*/

// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

interface IIdentityContract {  
    function getClass(uint256 tokenId) external view returns (string memory);
    
    function getRace(uint256 tokenId) external view returns (string memory);
    
    function getStrength(uint256 tokenId) external view returns (string memory);

    function getIntelligence(uint256 tokenId) external view returns (string memory);
    
    function getAttractiveness(uint256 tokenId) external view returns (string memory);
    
    function getTechSkill(uint256 tokenId) external view returns (string memory);
    
    function getCool(uint256 tokenId) external view returns (string memory);

    function getEyes(uint256 tokenId) external view returns (string memory);

    function getAbility(uint256 tokenId) external view returns (string memory);

    function getGender(uint256 tokenId) external view returns (string memory);
}

interface IVaultContract {
    function getAdditionalItem(uint256 tokenId) external view returns (string memory);

    function getCreditMultiplier(uint256 tokenId) external view returns (string memory);
}

interface IItemsContract {
    function getWeapon(uint256 tokenId) external view returns (string memory);

    function getVehicle(uint256 tokenId) external view returns (string memory);
    
    function getApparel(uint256 tokenId) external view returns (string memory);

    function getHelm(uint256 tokenId) external view returns (string memory);
}

interface ILandContract {
    function getLocation(uint256 tokenId) external view returns (string memory);
}

interface IParentContract {
    function getIdentityIdOfTokenId(uint256 citizenId) external view returns (uint256);

    function getVaultIdOfTokenId(uint256 citizenId) external view returns (uint256);

    function getItemCacheIdOfTokenId(uint256 citizenId) external view returns (uint256);

    function getLandDeedIdOfTokenId(uint256 citizenId) external view returns (uint256);

    function getSpecialMessageOfTokenId(uint256 citizenId) external view returns (string memory);

    function getRewardRateOfTokenId(uint256 citizenId) external view returns (uint256);
}

/**
 * @dev Interface of the ERC165 standard, as defined in the
 * https://eips.ethereum.org/EIPS/eip-165[EIP].
 *
 * Implementers can declare support of contract interfaces, which can then be
 * queried by others ({ERC165Checker}).
 *
 * For an implementation, see {ERC165}.
 */
interface IERC165 {
    /**
     * @dev Returns true if this contract implements the interface defined by
     * `interfaceId`. See the corresponding
     * https://eips.ethereum.org/EIPS/eip-165#how-interfaces-are-identified[EIP section]
     * to learn more about how these ids are created.
     *
     * This function call must use less than 30 000 gas.
     */
    function supportsInterface(bytes4 interfaceId) external view returns (bool);
}

/*
 * @dev Provides information about the current execution context, including the
 * sender of the transaction and its data. While these are generally available
 * via msg.sender and msg.data, they should not be accessed in such a direct
 * manner, since when dealing with meta-transactions the account sending and
 * paying for execution may not be the actual sender (as far as an application
 * is concerned).
 *
 * This contract is only required for intermediate, library-like contracts.
 */
abstract contract Context {
    function _msgSender() internal view virtual returns (address) {
        return msg.sender;
    }

    function _msgData() internal view virtual returns (bytes calldata) {
        return msg.data;
    }
}

/**
 * @dev Contract module which provides a basic access control mechanism, where
 * there is an account (an owner) that can be granted exclusive access to
 * specific functions.
 *
 * By default, the owner account will be the one that deploys the contract. This
 * can later be changed with {transferOwnership}.
 *
 * This module is used through inheritance. It will make available the modifier
 * `onlyOwner`, which can be applied to your functions to restrict their use to
 * the owner.
 */
abstract contract Ownable is Context {
    address private _owner;

    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    /**
     * @dev Initializes the contract setting the deployer as the initial owner.
     */
    constructor() {
        _setOwner(_msgSender());
    }

    /**
     * @dev Returns the address of the current owner.
     */
    function owner() public view virtual returns (address) {
        return _owner;
    }

    /**
     * @dev Throws if called by any account other than the owner.
     */
    modifier onlyOwner() {
        require(owner() == _msgSender(), "Ownable: caller is not the owner");
        _;
    }

    /**
     * @dev Leaves the contract without owner. It will not be possible to call
     * `onlyOwner` functions anymore. Can only be called by the current owner.
     *
     * NOTE: Renouncing ownership will leave the contract without an owner,
     * thereby removing any functionality that is only available to the owner.
     */
    function renounceOwnership() public virtual onlyOwner {
        _setOwner(address(0));
    }

    /**
     * @dev Transfers ownership of the contract to a new account (`newOwner`).
     * Can only be called by the current owner.
     */
    function transferOwnership(address newOwner) public virtual onlyOwner {
        require(newOwner != address(0), "Ownable: new owner is the zero address");
        _setOwner(newOwner);
    }

    function _setOwner(address newOwner) private {
        address oldOwner = _owner;
        _owner = newOwner;
        emit OwnershipTransferred(oldOwner, newOwner);
    }
}

contract NTCitizenHandMint is Ownable {

    address identityContract;
    address parentContract;
    address handCitizenContract;


    string[] private class = [
        "Hand of Citadel",
        "Hand of Citadel",
        "Hand of Citadel",
        "Hand of Citadel",
        "Hand of Citadel",
        "Hand of Citadel",
        "Hand of Citadel"
    ];
    
    string[] private gender = [
        "Male",
        "Male",
        "Female",
        "Male",
        "",
        "",
        ""
    ];
    
    string[7] private race = [
        "Devil",
        "Saint",
        "Survivor",
        "Destroyer",
        "",
        "",
        ""
    ];

    string[7] private ability = [
        "Damn",
        "Bless",
        "Invest",
        "Carnage",
        "",
        "",
        ""
    ];

    string[7] private eyes = [
        "Demon",
        "Angelic",
        "Focused",
        "Cybernetic Optics",
        "",
        "",
        ""
    ];

    string[] private creditYield = [
        "High",
        "High",
        "High",
        "High",
        "High",
        "High",
        "High"
    ];

    string[7] private additionalItem = [
        "1 Bitcoin",
        "Cyber Penguin",
        "1 Dogecoin",
        "Katanas",
        "",
        "",
        ""
    ];

    string[7] private creditMultiplier = [
        "?",
        "?",
        "?",
        "?",
        "?",
        "?",
        "?"
    ];

    string[7] private vehicle = [
        "Gamborghini",
        "Epic Mount",
        "Hover Car",
        "War Rig",
        "",
        "",
        ""
    ];

    string[7] private weapon = [
       "Super Shotgun",
       "Buster Sword",
       "Golden Magnum",
       "Mini Gun",
       "",
       "",
       ""
    ];

    string[7] private apparel = [
        "Devil Armor",
        "Saint Armor",
        "Byte Suit",
        "Samson",
        "",
        "",
        ""
    ];

    string[7] private helm = [
        "Reaper Helm",
        "Saint Helm",
        "Electric Tiger Helm",
        "Mecha Mask",
        "",
        "",
        ""
    ];

    string[7] private location = [
        "Omnipresent",
        "Omnipresent",
        "Omnipresent",
        "Omnipresent",
        "",
        "",
        ""
    ];

    string[7] private imgURL;
    
    function random(string memory input) internal pure returns (uint256) {
        return uint256(keccak256(abi.encodePacked(input)));
    }

    function setIMGUrl(uint256 index, string memory input) external onlyOwner
    {
        require(index < 7, "Index out of range");
        imgURL[index] = input;
    }

    function setIdentityContract(address _address) external onlyOwner
    {
        identityContract = _address;
    }

    function setParentContract(address _address) external onlyOwner
    {
        parentContract = _address;
    }

    function setGenderArray(uint256 index, string memory value) external onlyOwner
    {
        require(index < 7, "Index out of range");
        gender[index] = value;
    }

    function setRaceArray(uint256 index, string memory value) external onlyOwner
    {
        require(index < 7, "Index out of range");
        race[index] = value;
    }

    function setAbilityArray(uint256 index, string memory value) external onlyOwner
    {
        require(index < 7, "Index out of range");
        ability[index] = value;
    }

    function setEyesArray(uint256 index, string memory value) external onlyOwner
    {
        require(index < 7, "Index out of range");
        eyes[index] = value;
    }

    function setCreditYieldArray(uint256 index, string memory value) external onlyOwner
    {
        require(index < 7, "Index out of range");
        creditYield[index] = value;
    }

    function setAdditionalItemArray(uint256 index, string memory value) external onlyOwner
    {
        require(index < 7, "Index out of range");
        additionalItem[index] = value;
    }

    function setCreditMultiplierArray(uint256 index, string memory value) external onlyOwner
    {
        require(index < 7, "Index out of range");
        creditMultiplier[index] = value;
    }

    function setWeaponArray(uint256 index, string memory value) external onlyOwner
    {
        require(index < 7, "Index out of range");
        weapon[index] = value;
    }

    function setApparelArray(uint256 index, string memory value) external onlyOwner
    {
        require(index < 7, "Index out of range");
        apparel[index] = value;
    }

    function setVehicleArray(uint256 index, string memory value) external onlyOwner
    {
        require(index < 7, "Index out of range");
        vehicle[index] = value;
    }

    function setHelmArray(uint256 index, string memory value) external onlyOwner
    {
        require(index < 7, "Index out of range");
        helm[index] = value;
    }

    function setLocationArray(uint256 index, string memory value) external onlyOwner
    {
        require(index < 7, "Index out of range");
        location[index] = value;
    }


    function getClass(uint256 tokenId) public view returns (string memory){
        IIdentityContract dataContract;

        dataContract = IIdentityContract(identityContract);

        return dataContract.getClass(tokenId);
    }
    
    function getRace(uint256 tokenId) public view returns (string memory){
        IIdentityContract dataContract;

        dataContract = IIdentityContract(identityContract);

        return dataContract.getRace(tokenId);
    }
    
    function getStrength(uint256 tokenId) public view returns (string memory){
        IIdentityContract dataContract;

        dataContract = IIdentityContract(identityContract);

        return dataContract.getStrength(tokenId);
    }

    function getIntelligence(uint256 tokenId) public view returns (string memory){
        IIdentityContract dataContract;

        dataContract = IIdentityContract(identityContract);
        
        return dataContract.getIntelligence(tokenId);
    }
    
    function getAttractiveness(uint256 tokenId) public view returns (string memory){
        IIdentityContract dataContract;
        
        dataContract = IIdentityContract(identityContract);
        
        return dataContract.getAttractiveness(tokenId);
    }
    
    function getTechSkill(uint256 tokenId) public view returns (string memory){
        IIdentityContract dataContract;
       
        dataContract = IIdentityContract(identityContract);
        
        return dataContract.getTechSkill(tokenId);
    }
    
    function getCool(uint256 tokenId) public view returns (string memory){
        IIdentityContract dataContract;
        
        dataContract = IIdentityContract(identityContract);
        
        return dataContract.getCool(tokenId);
    }

    function getEyes(uint256 tokenId) public view returns (string memory){
        IIdentityContract dataContract;
        
        dataContract = IIdentityContract(identityContract);
        
        return dataContract.getEyes(tokenId);
    }

    function getAbility(uint256 tokenId) public view returns (string memory){
        IIdentityContract dataContract;
        
        dataContract = IIdentityContract(identityContract);
        
        return dataContract.getAbility(tokenId);
    }

    function getGender(uint256 tokenId) public view returns (string memory){
        IIdentityContract dataContract;
        
        dataContract = IIdentityContract(identityContract);
        
        return dataContract.getGender(tokenId);
    }

    function getAdditionalItem(uint256 tokenId) public view returns (string memory) {
        return additionalItem[tokenId - 2281];
    }

    function getCreditMultiplier(uint256 tokenId) public view returns (string memory) {
        return creditMultiplier[tokenId - 2281];
    }

    function getWeapon(uint256 tokenId) public view returns (string memory)
    {
        return weapon[tokenId - 2281];
    }

    function getVehicle(uint256 tokenId) public view returns (string memory)
    {
        return vehicle[tokenId - 2281];
    }
    
    function getApparel(uint256 tokenId) public view returns (string memory) {
        return apparel[tokenId - 2281];
    }

    function getHelm(uint256 tokenId) public view returns (string memory) 
    {
        return helm[tokenId - 2281];
    }

    function getLocation(uint256 tokenId) public view returns (string memory) {
        return location[tokenId - 2281];
    }

    function getIdentityId(uint256 tokenId) internal view returns (uint256)
    {
        IParentContract parentCallerContract = IParentContract(parentContract);
        return parentCallerContract.getIdentityIdOfTokenId(tokenId);
    }

    function getRewardRate(uint256 tokenId) internal view returns (uint256)
    {
        IParentContract parentCallerContract = IParentContract(parentContract);
        return parentCallerContract.getRewardRateOfTokenId(tokenId);
    }

    function getSpecialMessage(uint256 tokenId) internal view returns (string memory)
    {
        IParentContract parentCallerContract = IParentContract(parentContract);
        return parentCallerContract.getSpecialMessageOfTokenId(tokenId);
    }

    function createImage(uint256 tokenId) internal view returns (string memory)
    {
        string memory output;

        output = generateLayers(tokenId);
        return output;
    }
    // Hand of Citadel only has 1 layer
    function generateLayers(uint256 tokenId) internal view returns (string memory)
    {
        string memory output;

        output = string(abi.encodePacked(output, packLayer(string(abi.encodePacked(imgURL[getIdentityId(tokenId) - 2281])))));

        return output;
    }

    function packLayer(string memory url) internal pure returns (string memory)
    {
        if(bytes(url).length > 0)
        {
            return string(abi.encodePacked('<image href="', url, '"/>'));
        }
        return '';
    }

    function packMetaAttributes(uint256 tokenId) internal view returns (string memory)
    {
        uint256 identityId = getIdentityId(tokenId);
        
        string memory output = string(abi.encodePacked('{"name": "Citizen #', toString(tokenId), '","attributes": [{"trait_type": "Class", "value": "', getClass(identityId), '"},{"trait_type": "Race", "value": "', getRace(identityId), '"},{"trait_type": "Strength", "max_value": 100, "value": ', getStrength(identityId), '},{"trait_type": "Intelligence", "max_value": 100, "value": ', getIntelligence(identityId), '},{"trait_type": "Attractiveness", "max_value": 100, "value": ', getAttractiveness(identityId), '},{"trait_type": "Tech Skill", "max_value": 100, "value": '));

        output = string(abi.encodePacked(output, getTechSkill(identityId), '},{"trait_type": "Cool", "max_value": 100, "value": ', getCool(identityId), '},{"trait_type": "Eyes", "value": "', getEyes(identityId), '"},{"trait_type": "Ability", "value": "', getAbility(identityId), '"},{"trait_type": "Location", "value": "', getLocation(identityId)));
        output = string(abi.encodePacked(output, '"},{"trait_type": "Additional Item", "value": "', getAdditionalItem(identityId), '"},{"trait_type": "Weapon", "value": "', getWeapon(identityId), '"},{"trait_type": "Vehicle", "value": "', getVehicle(identityId), '"},{"trait_type": "Apparel", "value": "', getApparel(identityId), '"},{"trait_type": "Helm", "value": "', getHelm(identityId)));
         output = string(abi.encodePacked(output, '"},{"trait_type": "Reward Rate", "value": ', toString(getRewardRate(tokenId)), '},{"trait_type": "Gender", "value": "', getGender(identityId),'"}],'));

        return output;
    }
    
    function generateURI(uint256 tokenId) public view returns (string memory) {

        string[3] memory parts;

        parts[0] = '<svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMinYMin meet" viewBox="0 0 1200 1200">';

        parts[1] = createImage(tokenId);

        parts[2] = '</svg>';

        string memory output = string(abi.encodePacked(parts[0], parts[1], parts[2]));

        string memory strAttributes = packMetaAttributes(tokenId);
        
        string memory json = Base64.encode(bytes(string(abi.encodePacked(strAttributes, '"description": "', getSpecialMessage(tokenId),'", "image_data": "data:image/svg+xml;base64,', Base64.encode(bytes(output)), '"}'))));
        output = string(abi.encodePacked('data:application/json;base64,', json));

        return output;
    }
    
    function toString(uint256 value) internal pure returns (string memory) {
    // Inspired by OraclizeAPI's implementation - MIT license
    // https://github.com/oraclize/ethereum-api/blob/b42146b063c7d6ee1358846c198246239e9360e8/oraclizeAPI_0.4.25.sol

        if (value == 0) {
            return "0";
        }
        uint256 temp = value;
        uint256 digits;
        while (temp != 0) {
            digits++;
            temp /= 10;
        }
        bytes memory buffer = new bytes(digits);
        while (value != 0) {
            digits -= 1;
            buffer[digits] = bytes1(uint8(48 + uint256(value % 10)));
            value /= 10;
        }
        return string(buffer);
    }

    function strToUint(string memory _str) public pure returns(uint256 res, bool err) {
    
        for (uint256 i = 0; i < bytes(_str).length; i++) 
        {
            if ((uint8(bytes(_str)[i]) - 48) < 0 || (uint8(bytes(_str)[i]) - 48) > 9) 
            {
                return (0, false);
            }
            res += (uint8(bytes(_str)[i]) - 48) * 10**(bytes(_str).length - i - 1);
        }
    
        return (res, true);
    }

    function strLengthChecker(string memory _string) internal pure returns (uint256)
    {
        return bytes(_string).length;
    }

    function memcmp(bytes memory a, bytes memory b) internal pure returns(bool){
        return (a.length == b.length) && (keccak256(a) == keccak256(b));
    }

    function strcmp(string memory a, string memory b) internal pure returns(bool){
        return memcmp(bytes(a), bytes(b));
    }

    /*
    * Created by @Thrasher66099 to check if a string exists in an array of strings.
    */
    function strArrayCmp(string[] memory a, string memory b, uint startIndex, uint count) internal pure returns(bool){

        for(uint i = startIndex; i < (startIndex + count); i++)
        {
            if(strcmp(a[i], b))
            {
                return true;
            }
        }

        return false;
    }
    
    constructor() Ownable() {
        identityContract = 0x86357A19E5537A8Fba9A004E555713BC943a66C0;
        parentContract = 0xb668beB1Fa440F6cF2Da0399f8C28caB993Bdd65;
        imgURL[0] = "https://neotokyo.mypinata.cloud/ipfs/QmTAoZ6aFVHGxzCpJ4dfMTs9UKDBSvwo3Rs6JwHorqrk1M";
        imgURL[1] = "https://neotokyo.mypinata.cloud/ipfs/QmVUY1xTHAyduu2L5Lyp57FS7NH5Bvn1SC96U7t81kqepm";
        imgURL[2] = "https://neotokyo.mypinata.cloud/ipfs/QmVk46iQukFVq4KzsjK89dUfJb171bMLktpbmKaoQ9pfb6";
        imgURL[3] = "https://neotokyo.mypinata.cloud/ipfs/QmRJeBuH5fepbYXZur62Eu3CZtTJ1h6NobX8ZJuWSuuJCE";
        imgURL[4] = "";
        imgURL[5] = "";
        imgURL[6] = "";
    }
}


/// [MIT License]
/// @title Base64
/// @notice Provides a function for encoding some bytes in base64
/// @author Brecht Devos <brecht@loopring.org>
library Base64 {
    bytes internal constant TABLE = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

    /// @notice Encodes some bytes to the base64 representation
    function encode(bytes memory data) internal pure returns (string memory) {
        uint256 len = data.length;
        if (len == 0) return "";

        // multiply by 4/3 rounded up
        uint256 encodedLen = 4 * ((len + 2) / 3);

        // Add some extra buffer at the end
        bytes memory result = new bytes(encodedLen + 32);

        bytes memory table = TABLE;

        assembly {
            let tablePtr := add(table, 1)
            let resultPtr := add(result, 32)

            for {
                let i := 0
            } lt(i, len) {

            } {
                i := add(i, 3)
                let input := and(mload(add(data, i)), 0xffffff)

                let out := mload(add(tablePtr, and(shr(18, input), 0x3F)))
                out := shl(8, out)
                out := add(out, and(mload(add(tablePtr, and(shr(12, input), 0x3F))), 0xFF))
                out := shl(8, out)
                out := add(out, and(mload(add(tablePtr, and(shr(6, input), 0x3F))), 0xFF))
                out := shl(8, out)
                out := add(out, and(mload(add(tablePtr, and(input, 0x3F))), 0xFF))
                out := shl(224, out)

                mstore(resultPtr, out)

                resultPtr := add(resultPtr, 4)
            }

            switch mod(len, 3)
            case 1 {
                mstore(sub(resultPtr, 2), shl(240, 0x3d3d))
            }
            case 2 {
                mstore(sub(resultPtr, 1), shl(248, 0x3d))
            }

            mstore(result, encodedLen)
        }

        return string(result);
    }
}